---
title: "To Do"
author: "Sean Wu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ToDo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# Dev Team To-do:

### TO-DO:
  * put next thing here.
  * Add aging to Human and HumanPop
  * Better data logging for MacroTile
  * in MacroTile::initialize(), make travelHabit arg 'n' part of HumanPop_PAR
  * look into jsonlite::stream_out
  * getEIP_MacroMosquitoPop should eventually return something besides an integer
  * See simMacro: need single call to Tile to do all aquatic ecology stuffs; needs to generalize across allocation possible aquatic ecology modules.
  * AQUA-Macro-Emerge.R should be split according to how AQUA-Micro-Queues.R and AQUA-Micro-Emerge.R is structured.
  * MACRO Emergence stuffs is called season right now...need to change to lambda
  * Rename MACRO-Human-Movment.R stuff to MACRO-Human-Travel.R (Movement to Travel) for consistency with online docs.
  * In set_humanPfSI() make it dependent on the PfSI_PAR vector in the class.

### SOLVED TO-DO:
  * SOLVED (Z not updating correctly, see MACRO-MosquitoPop-Methods.R) HumanPop$debug("queueInfectiousBites"): do debugging: EIR is always 0
  * SOVLED (see HUMANS-HumanPop-Parameters.R)check why in HumanPop$tStart is a vector.
  * Need to fix how infectious mosquitoes are generated in MACRO; non infectious humans should contribute to kappa but NOT to the generation of infectious mosquitoes. Ask if kappa should only accumulate biting propensities from infected individuals, it should because it is used to generate new infected mosquitoes..
