// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_human
void test_human();
RcppExport SEXP _MACROv2_test_human() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_human();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MACROv2_test_human", (DL_FUNC) &_MACROv2_test_human, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_MACROv2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
