// Generated by RcppR6 (0.2.4): do not edit by hand
#ifndef _MASHCPP_RCPPR6_PRE_HPP_
#define _MASHCPP_RCPPR6_PRE_HPP_

#include <RcppCommon.h>


namespace MASHcpp {
namespace RcppR6 {
template <typename T> class RcppR6;
}
}

namespace MASHcpp { class HumanEventQ; }
namespace MASHcpp { class HistoryGeneric; }
namespace MASHcpp { class HistoryTravel; }
namespace MASHcpp { class humanPfSI; }
namespace MASHcpp { class mosquitoPfSI; }
namespace MASHcpp { class humanPfMOI; }
namespace MASHcpp { class mosquitoPfMOI; }
namespace MASHcpp { class RiskQ; }
namespace MASHcpp { class ImagoQ; }
namespace MASHcpp { class EggQ; }
namespace MASHcpp { class EL4P; }
namespace MASHcpp { class ELPool; }
namespace MASHcpp { class MosquitoFemaleHistory; }

namespace Rcpp {
template <typename T> SEXP wrap(const MASHcpp::RcppR6::RcppR6<T>&);
namespace traits {
template <typename T> class Exporter<MASHcpp::RcppR6::RcppR6<T> >;
}

template <> SEXP wrap(const MASHcpp::HumanEventQ&);
template <> MASHcpp::HumanEventQ as(SEXP);
template <> SEXP wrap(const MASHcpp::HistoryGeneric&);
template <> MASHcpp::HistoryGeneric as(SEXP);
template <> SEXP wrap(const MASHcpp::HistoryTravel&);
template <> MASHcpp::HistoryTravel as(SEXP);
template <> SEXP wrap(const MASHcpp::humanPfSI&);
template <> MASHcpp::humanPfSI as(SEXP);
template <> SEXP wrap(const MASHcpp::mosquitoPfSI&);
template <> MASHcpp::mosquitoPfSI as(SEXP);
template <> SEXP wrap(const MASHcpp::humanPfMOI&);
template <> MASHcpp::humanPfMOI as(SEXP);
template <> SEXP wrap(const MASHcpp::mosquitoPfMOI&);
template <> MASHcpp::mosquitoPfMOI as(SEXP);
template <> SEXP wrap(const MASHcpp::RiskQ&);
template <> MASHcpp::RiskQ as(SEXP);
template <> SEXP wrap(const MASHcpp::ImagoQ&);
template <> MASHcpp::ImagoQ as(SEXP);
template <> SEXP wrap(const MASHcpp::EggQ&);
template <> MASHcpp::EggQ as(SEXP);
template <> SEXP wrap(const MASHcpp::EL4P&);
template <> MASHcpp::EL4P as(SEXP);
template <> SEXP wrap(const MASHcpp::ELPool&);
template <> MASHcpp::ELPool as(SEXP);
template <> SEXP wrap(const MASHcpp::MosquitoFemaleHistory&);
template <> MASHcpp::MosquitoFemaleHistory as(SEXP);
}

#endif
