# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_MACRO_rcpp_hello_world', PACKAGE = 'MACRO')
}

#'@export
testEventQueue <- function() {
    invisible(.Call('_MACRO_testEventQueue', PACKAGE = 'MACRO'))
}

#'@export
testHuman <- function() {
    invisible(.Call('_MACRO_testHuman', PACKAGE = 'MACRO'))
}

#'@export
testHumanQ <- function() {
    invisible(.Call('_MACRO_testHumanQ', PACKAGE = 'MACRO'))
}

