# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_hello_world <- function() {
    .Call('_MICRO_rcpp_hello_world', PACKAGE = 'MICRO')
}

#' @export
testJSON <- function(outfile, numvec, charvec) {
    invisible(.Call('_MICRO_testJSON', PACKAGE = 'MICRO', outfile, numvec, charvec))
}

