// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/MASH.h"
#include <Rcpp.h>

using namespace Rcpp;

// util_PfSIoneHistory
void util_PfSIoneHistory(const Rcpp::List& historyIxH, const NumericVector& timeBins, NumericMatrix timeSeries);
RcppExport SEXP _MASH_util_PfSIoneHistory(SEXP historyIxHSEXP, SEXP timeBinsSEXP, SEXP timeSeriesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type historyIxH(historyIxHSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type timeBins(timeBinsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type timeSeries(timeSeriesSEXP);
    util_PfSIoneHistory(historyIxH, timeBins, timeSeries);
    return R_NilValue;
END_RCPP
}
// HumanEventQ__ctor
MASH::HumanEventQ HumanEventQ__ctor(int initQ);
RcppExport SEXP _MASH_HumanEventQ__ctor(SEXP initQSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type initQ(initQSEXP);
    rcpp_result_gen = Rcpp::wrap(HumanEventQ__ctor(initQ));
    return rcpp_result_gen;
END_RCPP
}
// HumanEventQ__firstEvent
Rcpp::List HumanEventQ__firstEvent(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_);
RcppExport SEXP _MASH_HumanEventQ__firstEvent(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(HumanEventQ__firstEvent(obj_));
    return rcpp_result_gen;
END_RCPP
}
// HumanEventQ__firstTime
int HumanEventQ__firstTime(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_);
RcppExport SEXP _MASH_HumanEventQ__firstTime(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(HumanEventQ__firstTime(obj_));
    return rcpp_result_gen;
END_RCPP
}
// HumanEventQ__rmFirstEventFromQ
void HumanEventQ__rmFirstEventFromQ(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_);
RcppExport SEXP _MASH_HumanEventQ__rmFirstEventFromQ(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    HumanEventQ__rmFirstEventFromQ(obj_);
    return R_NilValue;
END_RCPP
}
// HumanEventQ__rmTagFromQ
void HumanEventQ__rmTagFromQ(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_, std::string tag);
RcppExport SEXP _MASH_HumanEventQ__rmTagFromQ(SEXP obj_SEXP, SEXP tagSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< std::string >::type tag(tagSEXP);
    HumanEventQ__rmTagFromQ(obj_, tag);
    return R_NilValue;
END_RCPP
}
// HumanEventQ__get_queueN
int HumanEventQ__get_queueN(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_);
RcppExport SEXP _MASH_HumanEventQ__get_queueN(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(HumanEventQ__get_queueN(obj_));
    return rcpp_result_gen;
END_RCPP
}
// HumanEventQ__addEvent2Q
void HumanEventQ__addEvent2Q(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_, Rcpp::List event);
RcppExport SEXP _MASH_HumanEventQ__addEvent2Q(SEXP obj_SEXP, SEXP eventSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type event(eventSEXP);
    HumanEventQ__addEvent2Q(obj_, event);
    return R_NilValue;
END_RCPP
}
// HumanEventQ__get_EventQ
Rcpp::List HumanEventQ__get_EventQ(MASH::RcppR6::RcppR6<MASH::HumanEventQ> obj_);
RcppExport SEXP _MASH_HumanEventQ__get_EventQ(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HumanEventQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(HumanEventQ__get_EventQ(obj_));
    return rcpp_result_gen;
END_RCPP
}
// HistoryGeneric__ctor
MASH::HistoryGeneric HistoryGeneric__ctor(int N);
RcppExport SEXP _MASH_HistoryGeneric__ctor(SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(HistoryGeneric__ctor(N));
    return rcpp_result_gen;
END_RCPP
}
// HistoryGeneric__track_history
void HistoryGeneric__track_history(MASH::RcppR6::RcppR6<MASH::HistoryGeneric> obj_, double tEvent, std::string event);
RcppExport SEXP _MASH_HistoryGeneric__track_history(SEXP obj_SEXP, SEXP tEventSEXP, SEXP eventSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HistoryGeneric> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type tEvent(tEventSEXP);
    Rcpp::traits::input_parameter< std::string >::type event(eventSEXP);
    HistoryGeneric__track_history(obj_, tEvent, event);
    return R_NilValue;
END_RCPP
}
// HistoryGeneric__get_history
Rcpp::List HistoryGeneric__get_history(MASH::RcppR6::RcppR6<MASH::HistoryGeneric> obj_);
RcppExport SEXP _MASH_HistoryGeneric__get_history(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HistoryGeneric> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(HistoryGeneric__get_history(obj_));
    return rcpp_result_gen;
END_RCPP
}
// HistoryTravel__ctor
MASH::HistoryTravel HistoryTravel__ctor(int N);
RcppExport SEXP _MASH_HistoryTravel__ctor(SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(HistoryTravel__ctor(N));
    return rcpp_result_gen;
END_RCPP
}
// HistoryTravel__track_travel
void HistoryTravel__track_travel(MASH::RcppR6::RcppR6<MASH::HistoryTravel> obj_, double tTravel, int locationH);
RcppExport SEXP _MASH_HistoryTravel__track_travel(SEXP obj_SEXP, SEXP tTravelSEXP, SEXP locationHSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HistoryTravel> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type tTravel(tTravelSEXP);
    Rcpp::traits::input_parameter< int >::type locationH(locationHSEXP);
    HistoryTravel__track_travel(obj_, tTravel, locationH);
    return R_NilValue;
END_RCPP
}
// HistoryTravel__get_travelHistory
Rcpp::List HistoryTravel__get_travelHistory(MASH::RcppR6::RcppR6<MASH::HistoryTravel> obj_);
RcppExport SEXP _MASH_HistoryTravel__get_travelHistory(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::HistoryTravel> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(HistoryTravel__get_travelHistory(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__ctor
MASH::humanPfSI humanPfSI__ctor(int PfID_init, double tInf_init, double b_init, double c_init, int damID_init, int sireID_init, bool infected_init, bool chemoprophylaxis_init);
RcppExport SEXP _MASH_humanPfSI__ctor(SEXP PfID_initSEXP, SEXP tInf_initSEXP, SEXP b_initSEXP, SEXP c_initSEXP, SEXP damID_initSEXP, SEXP sireID_initSEXP, SEXP infected_initSEXP, SEXP chemoprophylaxis_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type PfID_init(PfID_initSEXP);
    Rcpp::traits::input_parameter< double >::type tInf_init(tInf_initSEXP);
    Rcpp::traits::input_parameter< double >::type b_init(b_initSEXP);
    Rcpp::traits::input_parameter< double >::type c_init(c_initSEXP);
    Rcpp::traits::input_parameter< int >::type damID_init(damID_initSEXP);
    Rcpp::traits::input_parameter< int >::type sireID_init(sireID_initSEXP);
    Rcpp::traits::input_parameter< bool >::type infected_init(infected_initSEXP);
    Rcpp::traits::input_parameter< bool >::type chemoprophylaxis_init(chemoprophylaxis_initSEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__ctor(PfID_init, tInf_init, b_init, c_init, damID_init, sireID_init, infected_init, chemoprophylaxis_init));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__get_PfID
std::vector<int> humanPfSI__get_PfID(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_);
RcppExport SEXP _MASH_humanPfSI__get_PfID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__get_PfID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__push_PfID
void humanPfSI__push_PfID(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_, int PfID_new);
RcppExport SEXP _MASH_humanPfSI__push_PfID(SEXP obj_SEXP, SEXP PfID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type PfID_new(PfID_newSEXP);
    humanPfSI__push_PfID(obj_, PfID_new);
    return R_NilValue;
END_RCPP
}
// humanPfSI__back_PfID
int humanPfSI__back_PfID(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_);
RcppExport SEXP _MASH_humanPfSI__back_PfID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__back_PfID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__get_tInf
std::vector<double> humanPfSI__get_tInf(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_);
RcppExport SEXP _MASH_humanPfSI__get_tInf(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__get_tInf(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__push_tInf
void humanPfSI__push_tInf(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_, double tInf_new);
RcppExport SEXP _MASH_humanPfSI__push_tInf(SEXP obj_SEXP, SEXP tInf_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type tInf_new(tInf_newSEXP);
    humanPfSI__push_tInf(obj_, tInf_new);
    return R_NilValue;
END_RCPP
}
// humanPfSI__get_b
double humanPfSI__get_b(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_);
RcppExport SEXP _MASH_humanPfSI__get_b(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__get_b(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__set_b
void humanPfSI__set_b(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_, double b_new);
RcppExport SEXP _MASH_humanPfSI__set_b(SEXP obj_SEXP, SEXP b_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type b_new(b_newSEXP);
    humanPfSI__set_b(obj_, b_new);
    return R_NilValue;
END_RCPP
}
// humanPfSI__get_c
double humanPfSI__get_c(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_);
RcppExport SEXP _MASH_humanPfSI__get_c(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__get_c(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__set_c
void humanPfSI__set_c(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_, double c_new);
RcppExport SEXP _MASH_humanPfSI__set_c(SEXP obj_SEXP, SEXP c_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type c_new(c_newSEXP);
    humanPfSI__set_c(obj_, c_new);
    return R_NilValue;
END_RCPP
}
// humanPfSI__get_damID
std::vector<int> humanPfSI__get_damID(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_);
RcppExport SEXP _MASH_humanPfSI__get_damID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__get_damID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__push_damID
void humanPfSI__push_damID(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_, int damID_new);
RcppExport SEXP _MASH_humanPfSI__push_damID(SEXP obj_SEXP, SEXP damID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type damID_new(damID_newSEXP);
    humanPfSI__push_damID(obj_, damID_new);
    return R_NilValue;
END_RCPP
}
// humanPfSI__get_sireID
std::vector<int> humanPfSI__get_sireID(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_);
RcppExport SEXP _MASH_humanPfSI__get_sireID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__get_sireID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__push_sireID
void humanPfSI__push_sireID(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_, int sireID_new);
RcppExport SEXP _MASH_humanPfSI__push_sireID(SEXP obj_SEXP, SEXP sireID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type sireID_new(sireID_newSEXP);
    humanPfSI__push_sireID(obj_, sireID_new);
    return R_NilValue;
END_RCPP
}
// humanPfSI__get_infected
bool humanPfSI__get_infected(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_);
RcppExport SEXP _MASH_humanPfSI__get_infected(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__get_infected(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__set_infected
void humanPfSI__set_infected(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_, bool infected_new);
RcppExport SEXP _MASH_humanPfSI__set_infected(SEXP obj_SEXP, SEXP infected_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< bool >::type infected_new(infected_newSEXP);
    humanPfSI__set_infected(obj_, infected_new);
    return R_NilValue;
END_RCPP
}
// humanPfSI__get_chemoprophylaxis
bool humanPfSI__get_chemoprophylaxis(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_);
RcppExport SEXP _MASH_humanPfSI__get_chemoprophylaxis(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__get_chemoprophylaxis(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfSI__set_chemoprophylaxis
void humanPfSI__set_chemoprophylaxis(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_, bool chemoprophylaxis_new);
RcppExport SEXP _MASH_humanPfSI__set_chemoprophylaxis(SEXP obj_SEXP, SEXP chemoprophylaxis_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< bool >::type chemoprophylaxis_new(chemoprophylaxis_newSEXP);
    humanPfSI__set_chemoprophylaxis(obj_, chemoprophylaxis_new);
    return R_NilValue;
END_RCPP
}
// humanPfSI__track_history
void humanPfSI__track_history(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_, double tEvent, std::string event);
RcppExport SEXP _MASH_humanPfSI__track_history(SEXP obj_SEXP, SEXP tEventSEXP, SEXP eventSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type tEvent(tEventSEXP);
    Rcpp::traits::input_parameter< std::string >::type event(eventSEXP);
    humanPfSI__track_history(obj_, tEvent, event);
    return R_NilValue;
END_RCPP
}
// humanPfSI__get_history
Rcpp::List humanPfSI__get_history(MASH::RcppR6::RcppR6<MASH::humanPfSI> obj_);
RcppExport SEXP _MASH_humanPfSI__get_history(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfSI__get_history(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfSI__ctor
MASH::mosquitoPfSI mosquitoPfSI__ctor(int PfID_init, double tInf_init, int damID_init, int sireID_init, bool infected_init);
RcppExport SEXP _MASH_mosquitoPfSI__ctor(SEXP PfID_initSEXP, SEXP tInf_initSEXP, SEXP damID_initSEXP, SEXP sireID_initSEXP, SEXP infected_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type PfID_init(PfID_initSEXP);
    Rcpp::traits::input_parameter< double >::type tInf_init(tInf_initSEXP);
    Rcpp::traits::input_parameter< int >::type damID_init(damID_initSEXP);
    Rcpp::traits::input_parameter< int >::type sireID_init(sireID_initSEXP);
    Rcpp::traits::input_parameter< bool >::type infected_init(infected_initSEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfSI__ctor(PfID_init, tInf_init, damID_init, sireID_init, infected_init));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfSI__get_PfID
int mosquitoPfSI__get_PfID(MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> obj_);
RcppExport SEXP _MASH_mosquitoPfSI__get_PfID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfSI__get_PfID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfSI__set_PfID
void mosquitoPfSI__set_PfID(MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> obj_, int PfID_new);
RcppExport SEXP _MASH_mosquitoPfSI__set_PfID(SEXP obj_SEXP, SEXP PfID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type PfID_new(PfID_newSEXP);
    mosquitoPfSI__set_PfID(obj_, PfID_new);
    return R_NilValue;
END_RCPP
}
// mosquitoPfSI__get_tInf
double mosquitoPfSI__get_tInf(MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> obj_);
RcppExport SEXP _MASH_mosquitoPfSI__get_tInf(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfSI__get_tInf(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfSI__set_tInf
void mosquitoPfSI__set_tInf(MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> obj_, double tInf_new);
RcppExport SEXP _MASH_mosquitoPfSI__set_tInf(SEXP obj_SEXP, SEXP tInf_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type tInf_new(tInf_newSEXP);
    mosquitoPfSI__set_tInf(obj_, tInf_new);
    return R_NilValue;
END_RCPP
}
// mosquitoPfSI__get_damID
int mosquitoPfSI__get_damID(MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> obj_);
RcppExport SEXP _MASH_mosquitoPfSI__get_damID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfSI__get_damID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfSI__set_damID
void mosquitoPfSI__set_damID(MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> obj_, int damID_new);
RcppExport SEXP _MASH_mosquitoPfSI__set_damID(SEXP obj_SEXP, SEXP damID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type damID_new(damID_newSEXP);
    mosquitoPfSI__set_damID(obj_, damID_new);
    return R_NilValue;
END_RCPP
}
// mosquitoPfSI__get_sireID
int mosquitoPfSI__get_sireID(MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> obj_);
RcppExport SEXP _MASH_mosquitoPfSI__get_sireID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfSI__get_sireID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfSI__set_sireID
void mosquitoPfSI__set_sireID(MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> obj_, int sireID_new);
RcppExport SEXP _MASH_mosquitoPfSI__set_sireID(SEXP obj_SEXP, SEXP sireID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type sireID_new(sireID_newSEXP);
    mosquitoPfSI__set_sireID(obj_, sireID_new);
    return R_NilValue;
END_RCPP
}
// mosquitoPfSI__get_infected
bool mosquitoPfSI__get_infected(MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> obj_);
RcppExport SEXP _MASH_mosquitoPfSI__get_infected(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfSI__get_infected(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfSI__set_infected
void mosquitoPfSI__set_infected(MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> obj_, bool infected_new);
RcppExport SEXP _MASH_mosquitoPfSI__set_infected(SEXP obj_SEXP, SEXP infected_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfSI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< bool >::type infected_new(infected_newSEXP);
    mosquitoPfSI__set_infected(obj_, infected_new);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__ctor
MASH::humanPfMOI humanPfMOI__ctor(int PfID_init, double tInf_init, int MOI_init, double b_init, double c_init, int damID_init, int sireID_init, bool chemoprophylaxis_init);
RcppExport SEXP _MASH_humanPfMOI__ctor(SEXP PfID_initSEXP, SEXP tInf_initSEXP, SEXP MOI_initSEXP, SEXP b_initSEXP, SEXP c_initSEXP, SEXP damID_initSEXP, SEXP sireID_initSEXP, SEXP chemoprophylaxis_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type PfID_init(PfID_initSEXP);
    Rcpp::traits::input_parameter< double >::type tInf_init(tInf_initSEXP);
    Rcpp::traits::input_parameter< int >::type MOI_init(MOI_initSEXP);
    Rcpp::traits::input_parameter< double >::type b_init(b_initSEXP);
    Rcpp::traits::input_parameter< double >::type c_init(c_initSEXP);
    Rcpp::traits::input_parameter< int >::type damID_init(damID_initSEXP);
    Rcpp::traits::input_parameter< int >::type sireID_init(sireID_initSEXP);
    Rcpp::traits::input_parameter< bool >::type chemoprophylaxis_init(chemoprophylaxis_initSEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__ctor(PfID_init, tInf_init, MOI_init, b_init, c_init, damID_init, sireID_init, chemoprophylaxis_init));
    return rcpp_result_gen;
END_RCPP
}
// humanPfMOI__get_PfID
std::vector<int> humanPfMOI__get_PfID(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_);
RcppExport SEXP _MASH_humanPfMOI__get_PfID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__get_PfID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfMOI__push_PfID
void humanPfMOI__push_PfID(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, int PfID_new);
RcppExport SEXP _MASH_humanPfMOI__push_PfID(SEXP obj_SEXP, SEXP PfID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type PfID_new(PfID_newSEXP);
    humanPfMOI__push_PfID(obj_, PfID_new);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__get_tInf
std::vector<double> humanPfMOI__get_tInf(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_);
RcppExport SEXP _MASH_humanPfMOI__get_tInf(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__get_tInf(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfMOI__push_tInf
void humanPfMOI__push_tInf(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, double tInf_new);
RcppExport SEXP _MASH_humanPfMOI__push_tInf(SEXP obj_SEXP, SEXP tInf_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type tInf_new(tInf_newSEXP);
    humanPfMOI__push_tInf(obj_, tInf_new);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__get_MOI
int humanPfMOI__get_MOI(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_);
RcppExport SEXP _MASH_humanPfMOI__get_MOI(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__get_MOI(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfMOI__set_MOI
void humanPfMOI__set_MOI(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, int MOI_new);
RcppExport SEXP _MASH_humanPfMOI__set_MOI(SEXP obj_SEXP, SEXP MOI_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type MOI_new(MOI_newSEXP);
    humanPfMOI__set_MOI(obj_, MOI_new);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__get_b
double humanPfMOI__get_b(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_);
RcppExport SEXP _MASH_humanPfMOI__get_b(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__get_b(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfMOI__set_b
void humanPfMOI__set_b(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, double b_new);
RcppExport SEXP _MASH_humanPfMOI__set_b(SEXP obj_SEXP, SEXP b_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type b_new(b_newSEXP);
    humanPfMOI__set_b(obj_, b_new);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__get_c
double humanPfMOI__get_c(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_);
RcppExport SEXP _MASH_humanPfMOI__get_c(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__get_c(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfMOI__set_c
void humanPfMOI__set_c(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, double c_new);
RcppExport SEXP _MASH_humanPfMOI__set_c(SEXP obj_SEXP, SEXP c_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type c_new(c_newSEXP);
    humanPfMOI__set_c(obj_, c_new);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__get_damID
std::vector<int> humanPfMOI__get_damID(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_);
RcppExport SEXP _MASH_humanPfMOI__get_damID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__get_damID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfMOI__push_damID
void humanPfMOI__push_damID(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, int damID_new);
RcppExport SEXP _MASH_humanPfMOI__push_damID(SEXP obj_SEXP, SEXP damID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type damID_new(damID_newSEXP);
    humanPfMOI__push_damID(obj_, damID_new);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__get_sireID
std::vector<int> humanPfMOI__get_sireID(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_);
RcppExport SEXP _MASH_humanPfMOI__get_sireID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__get_sireID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfMOI__push_sireID
void humanPfMOI__push_sireID(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, int sireID_new);
RcppExport SEXP _MASH_humanPfMOI__push_sireID(SEXP obj_SEXP, SEXP sireID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type sireID_new(sireID_newSEXP);
    humanPfMOI__push_sireID(obj_, sireID_new);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__get_chemoprophylaxis
bool humanPfMOI__get_chemoprophylaxis(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_);
RcppExport SEXP _MASH_humanPfMOI__get_chemoprophylaxis(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__get_chemoprophylaxis(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfMOI__set_chemoprophylaxis
void humanPfMOI__set_chemoprophylaxis(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, bool chemoprophylaxis_new);
RcppExport SEXP _MASH_humanPfMOI__set_chemoprophylaxis(SEXP obj_SEXP, SEXP chemoprophylaxis_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< bool >::type chemoprophylaxis_new(chemoprophylaxis_newSEXP);
    humanPfMOI__set_chemoprophylaxis(obj_, chemoprophylaxis_new);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__add_Infection
void humanPfMOI__add_Infection(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, int PfID_new, int damID_new, int sireID_new);
RcppExport SEXP _MASH_humanPfMOI__add_Infection(SEXP obj_SEXP, SEXP PfID_newSEXP, SEXP damID_newSEXP, SEXP sireID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type PfID_new(PfID_newSEXP);
    Rcpp::traits::input_parameter< int >::type damID_new(damID_newSEXP);
    Rcpp::traits::input_parameter< int >::type sireID_new(sireID_newSEXP);
    humanPfMOI__add_Infection(obj_, PfID_new, damID_new, sireID_new);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__clear_Infection
void humanPfMOI__clear_Infection(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, int PfID_ix);
RcppExport SEXP _MASH_humanPfMOI__clear_Infection(SEXP obj_SEXP, SEXP PfID_ixSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type PfID_ix(PfID_ixSEXP);
    humanPfMOI__clear_Infection(obj_, PfID_ix);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__get_Infection
Rcpp::List humanPfMOI__get_Infection(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_);
RcppExport SEXP _MASH_humanPfMOI__get_Infection(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__get_Infection(obj_));
    return rcpp_result_gen;
END_RCPP
}
// humanPfMOI__track_history
void humanPfMOI__track_history(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_, double tEvent, std::string event);
RcppExport SEXP _MASH_humanPfMOI__track_history(SEXP obj_SEXP, SEXP tEventSEXP, SEXP eventSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type tEvent(tEventSEXP);
    Rcpp::traits::input_parameter< std::string >::type event(eventSEXP);
    humanPfMOI__track_history(obj_, tEvent, event);
    return R_NilValue;
END_RCPP
}
// humanPfMOI__get_history
Rcpp::List humanPfMOI__get_history(MASH::RcppR6::RcppR6<MASH::humanPfMOI> obj_);
RcppExport SEXP _MASH_humanPfMOI__get_history(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::humanPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(humanPfMOI__get_history(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfMOI__ctor
MASH::mosquitoPfMOI mosquitoPfMOI__ctor(int PfID_init, double tInf_init, int MOI_init, int damID_init, int sireID_init);
RcppExport SEXP _MASH_mosquitoPfMOI__ctor(SEXP PfID_initSEXP, SEXP tInf_initSEXP, SEXP MOI_initSEXP, SEXP damID_initSEXP, SEXP sireID_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type PfID_init(PfID_initSEXP);
    Rcpp::traits::input_parameter< double >::type tInf_init(tInf_initSEXP);
    Rcpp::traits::input_parameter< int >::type MOI_init(MOI_initSEXP);
    Rcpp::traits::input_parameter< int >::type damID_init(damID_initSEXP);
    Rcpp::traits::input_parameter< int >::type sireID_init(sireID_initSEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfMOI__ctor(PfID_init, tInf_init, MOI_init, damID_init, sireID_init));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfMOI__get_PfID
std::vector<int> mosquitoPfMOI__get_PfID(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_);
RcppExport SEXP _MASH_mosquitoPfMOI__get_PfID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfMOI__get_PfID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfMOI__push_PfID
void mosquitoPfMOI__push_PfID(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_, int PfID_new);
RcppExport SEXP _MASH_mosquitoPfMOI__push_PfID(SEXP obj_SEXP, SEXP PfID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type PfID_new(PfID_newSEXP);
    mosquitoPfMOI__push_PfID(obj_, PfID_new);
    return R_NilValue;
END_RCPP
}
// mosquitoPfMOI__get_tInf
std::vector<double> mosquitoPfMOI__get_tInf(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_);
RcppExport SEXP _MASH_mosquitoPfMOI__get_tInf(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfMOI__get_tInf(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfMOI__push_tInf
void mosquitoPfMOI__push_tInf(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_, double tInf_new);
RcppExport SEXP _MASH_mosquitoPfMOI__push_tInf(SEXP obj_SEXP, SEXP tInf_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type tInf_new(tInf_newSEXP);
    mosquitoPfMOI__push_tInf(obj_, tInf_new);
    return R_NilValue;
END_RCPP
}
// mosquitoPfMOI__get_MOI
int mosquitoPfMOI__get_MOI(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_);
RcppExport SEXP _MASH_mosquitoPfMOI__get_MOI(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfMOI__get_MOI(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfMOI__set_MOI
void mosquitoPfMOI__set_MOI(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_, int MOI_new);
RcppExport SEXP _MASH_mosquitoPfMOI__set_MOI(SEXP obj_SEXP, SEXP MOI_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type MOI_new(MOI_newSEXP);
    mosquitoPfMOI__set_MOI(obj_, MOI_new);
    return R_NilValue;
END_RCPP
}
// mosquitoPfMOI__get_damID
std::vector<int> mosquitoPfMOI__get_damID(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_);
RcppExport SEXP _MASH_mosquitoPfMOI__get_damID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfMOI__get_damID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfMOI__push_damID
void mosquitoPfMOI__push_damID(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_, int damID_new);
RcppExport SEXP _MASH_mosquitoPfMOI__push_damID(SEXP obj_SEXP, SEXP damID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type damID_new(damID_newSEXP);
    mosquitoPfMOI__push_damID(obj_, damID_new);
    return R_NilValue;
END_RCPP
}
// mosquitoPfMOI__get_sireID
std::vector<int> mosquitoPfMOI__get_sireID(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_);
RcppExport SEXP _MASH_mosquitoPfMOI__get_sireID(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfMOI__get_sireID(obj_));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfMOI__push_sireID
void mosquitoPfMOI__push_sireID(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_, int sireID_new);
RcppExport SEXP _MASH_mosquitoPfMOI__push_sireID(SEXP obj_SEXP, SEXP sireID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type sireID_new(sireID_newSEXP);
    mosquitoPfMOI__push_sireID(obj_, sireID_new);
    return R_NilValue;
END_RCPP
}
// mosquitoPfMOI__add_Infection
void mosquitoPfMOI__add_Infection(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_, int PfID_new, double tInf_new, int damID_new, int sireID_new);
RcppExport SEXP _MASH_mosquitoPfMOI__add_Infection(SEXP obj_SEXP, SEXP PfID_newSEXP, SEXP tInf_newSEXP, SEXP damID_newSEXP, SEXP sireID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type PfID_new(PfID_newSEXP);
    Rcpp::traits::input_parameter< double >::type tInf_new(tInf_newSEXP);
    Rcpp::traits::input_parameter< int >::type damID_new(damID_newSEXP);
    Rcpp::traits::input_parameter< int >::type sireID_new(sireID_newSEXP);
    mosquitoPfMOI__add_Infection(obj_, PfID_new, tInf_new, damID_new, sireID_new);
    return R_NilValue;
END_RCPP
}
// mosquitoPfMOI__get_Infection
Rcpp::List mosquitoPfMOI__get_Infection(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_, int PfID_ix);
RcppExport SEXP _MASH_mosquitoPfMOI__get_Infection(SEXP obj_SEXP, SEXP PfID_ixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type PfID_ix(PfID_ixSEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfMOI__get_Infection(obj_, PfID_ix));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfMOI__get_InfectionIx
Rcpp::List mosquitoPfMOI__get_InfectionIx(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_, int ix);
RcppExport SEXP _MASH_mosquitoPfMOI__get_InfectionIx(SEXP obj_SEXP, SEXP ixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type ix(ixSEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfMOI__get_InfectionIx(obj_, ix));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfMOI__get_InfectionEIP
Rcpp::List mosquitoPfMOI__get_InfectionEIP(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_, double incubation);
RcppExport SEXP _MASH_mosquitoPfMOI__get_InfectionEIP(SEXP obj_SEXP, SEXP incubationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type incubation(incubationSEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfMOI__get_InfectionEIP(obj_, incubation));
    return rcpp_result_gen;
END_RCPP
}
// mosquitoPfMOI__which_EIP
std::vector<int> mosquitoPfMOI__which_EIP(MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> obj_, double incubation);
RcppExport SEXP _MASH_mosquitoPfMOI__which_EIP(SEXP obj_SEXP, SEXP incubationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::mosquitoPfMOI> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type incubation(incubationSEXP);
    rcpp_result_gen = Rcpp::wrap(mosquitoPfMOI__which_EIP(obj_, incubation));
    return rcpp_result_gen;
END_RCPP
}
// RiskQ__ctor
MASH::RiskQ RiskQ__ctor();
RcppExport SEXP _MASH_RiskQ__ctor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(RiskQ__ctor());
    return rcpp_result_gen;
END_RCPP
}
// RiskQ__get_N
int RiskQ__get_N(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_);
RcppExport SEXP _MASH_RiskQ__get_N(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(RiskQ__get_N(obj_));
    return rcpp_result_gen;
END_RCPP
}
// RiskQ__set_N
void RiskQ__set_N(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_, int N_new);
RcppExport SEXP _MASH_RiskQ__set_N(SEXP obj_SEXP, SEXP N_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type N_new(N_newSEXP);
    RiskQ__set_N(obj_, N_new);
    return R_NilValue;
END_RCPP
}
// RiskQ__get_who
std::vector<int> RiskQ__get_who(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_);
RcppExport SEXP _MASH_RiskQ__get_who(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(RiskQ__get_who(obj_));
    return rcpp_result_gen;
END_RCPP
}
// RiskQ__push_who
void RiskQ__push_who(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_, int who_new);
RcppExport SEXP _MASH_RiskQ__push_who(SEXP obj_SEXP, SEXP who_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type who_new(who_newSEXP);
    RiskQ__push_who(obj_, who_new);
    return R_NilValue;
END_RCPP
}
// RiskQ__get_pTm
std::vector<double> RiskQ__get_pTm(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_);
RcppExport SEXP _MASH_RiskQ__get_pTm(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(RiskQ__get_pTm(obj_));
    return rcpp_result_gen;
END_RCPP
}
// RiskQ__push_pTm
void RiskQ__push_pTm(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_, double pTm_new);
RcppExport SEXP _MASH_RiskQ__push_pTm(SEXP obj_SEXP, SEXP pTm_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type pTm_new(pTm_newSEXP);
    RiskQ__push_pTm(obj_, pTm_new);
    return R_NilValue;
END_RCPP
}
// RiskQ__get_w
std::vector<double> RiskQ__get_w(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_);
RcppExport SEXP _MASH_RiskQ__get_w(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(RiskQ__get_w(obj_));
    return rcpp_result_gen;
END_RCPP
}
// RiskQ__push_w
void RiskQ__push_w(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_, double w_new);
RcppExport SEXP _MASH_RiskQ__push_w(SEXP obj_SEXP, SEXP w_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type w_new(w_newSEXP);
    RiskQ__push_w(obj_, w_new);
    return R_NilValue;
END_RCPP
}
// RiskQ__add_HumanHost
void RiskQ__add_HumanHost(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_, int who_new, double pTm_new, double w_new);
RcppExport SEXP _MASH_RiskQ__add_HumanHost(SEXP obj_SEXP, SEXP who_newSEXP, SEXP pTm_newSEXP, SEXP w_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type who_new(who_newSEXP);
    Rcpp::traits::input_parameter< double >::type pTm_new(pTm_newSEXP);
    Rcpp::traits::input_parameter< double >::type w_new(w_newSEXP);
    RiskQ__add_HumanHost(obj_, who_new, pTm_new, w_new);
    return R_NilValue;
END_RCPP
}
// RiskQ__get_HumanHost
Rcpp::List RiskQ__get_HumanHost(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_);
RcppExport SEXP _MASH_RiskQ__get_HumanHost(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(RiskQ__get_HumanHost(obj_));
    return rcpp_result_gen;
END_RCPP
}
// RiskQ__get_HumanHostIx
Rcpp::List RiskQ__get_HumanHostIx(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_, int ix);
RcppExport SEXP _MASH_RiskQ__get_HumanHostIx(SEXP obj_SEXP, SEXP ixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type ix(ixSEXP);
    rcpp_result_gen = Rcpp::wrap(RiskQ__get_HumanHostIx(obj_, ix));
    return rcpp_result_gen;
END_RCPP
}
// RiskQ__clear_HumanHost
void RiskQ__clear_HumanHost(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_);
RcppExport SEXP _MASH_RiskQ__clear_HumanHost(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    RiskQ__clear_HumanHost(obj_);
    return R_NilValue;
END_RCPP
}
// RiskQ__get_nOther
int RiskQ__get_nOther(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_);
RcppExport SEXP _MASH_RiskQ__get_nOther(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(RiskQ__get_nOther(obj_));
    return rcpp_result_gen;
END_RCPP
}
// RiskQ__set_nOther
void RiskQ__set_nOther(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_, int nOther_new);
RcppExport SEXP _MASH_RiskQ__set_nOther(SEXP obj_SEXP, SEXP nOther_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type nOther_new(nOther_newSEXP);
    RiskQ__set_nOther(obj_, nOther_new);
    return R_NilValue;
END_RCPP
}
// RiskQ__add_OtherHost
void RiskQ__add_OtherHost(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_, double otherW_new, int typeID_new);
RcppExport SEXP _MASH_RiskQ__add_OtherHost(SEXP obj_SEXP, SEXP otherW_newSEXP, SEXP typeID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type otherW_new(otherW_newSEXP);
    Rcpp::traits::input_parameter< int >::type typeID_new(typeID_newSEXP);
    RiskQ__add_OtherHost(obj_, otherW_new, typeID_new);
    return R_NilValue;
END_RCPP
}
// RiskQ__get_OtherHost
Rcpp::List RiskQ__get_OtherHost(MASH::RcppR6::RcppR6<MASH::RiskQ> obj_);
RcppExport SEXP _MASH_RiskQ__get_OtherHost(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::RiskQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(RiskQ__get_OtherHost(obj_));
    return rcpp_result_gen;
END_RCPP
}
// ImagoQ__ctor
MASH::ImagoQ ImagoQ__ctor();
RcppExport SEXP _MASH_ImagoQ__ctor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ImagoQ__ctor());
    return rcpp_result_gen;
END_RCPP
}
// ImagoQ__clear_ImagoQ
void ImagoQ__clear_ImagoQ(MASH::RcppR6::RcppR6<MASH::ImagoQ> obj_);
RcppExport SEXP _MASH_ImagoQ__clear_ImagoQ(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::ImagoQ> >::type obj_(obj_SEXP);
    ImagoQ__clear_ImagoQ(obj_);
    return R_NilValue;
END_RCPP
}
// ImagoQ__clear_ImagoQTime
void ImagoQ__clear_ImagoQTime(MASH::RcppR6::RcppR6<MASH::ImagoQ> obj_, double time);
RcppExport SEXP _MASH_ImagoQ__clear_ImagoQTime(SEXP obj_SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::ImagoQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    ImagoQ__clear_ImagoQTime(obj_, time);
    return R_NilValue;
END_RCPP
}
// ImagoQ__add_ImagoQ
void ImagoQ__add_ImagoQ(MASH::RcppR6::RcppR6<MASH::ImagoQ> obj_, int N_new, double tEmerge_new, int genotype_new, std::string damID_new, std::string sireID_new);
RcppExport SEXP _MASH_ImagoQ__add_ImagoQ(SEXP obj_SEXP, SEXP N_newSEXP, SEXP tEmerge_newSEXP, SEXP genotype_newSEXP, SEXP damID_newSEXP, SEXP sireID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::ImagoQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type N_new(N_newSEXP);
    Rcpp::traits::input_parameter< double >::type tEmerge_new(tEmerge_newSEXP);
    Rcpp::traits::input_parameter< int >::type genotype_new(genotype_newSEXP);
    Rcpp::traits::input_parameter< std::string >::type damID_new(damID_newSEXP);
    Rcpp::traits::input_parameter< std::string >::type sireID_new(sireID_newSEXP);
    ImagoQ__add_ImagoQ(obj_, N_new, tEmerge_new, genotype_new, damID_new, sireID_new);
    return R_NilValue;
END_RCPP
}
// ImagoQ__track_ImagoQ
double ImagoQ__track_ImagoQ(MASH::RcppR6::RcppR6<MASH::ImagoQ> obj_, double time);
RcppExport SEXP _MASH_ImagoQ__track_ImagoQ(SEXP obj_SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::ImagoQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(ImagoQ__track_ImagoQ(obj_, time));
    return rcpp_result_gen;
END_RCPP
}
// ImagoQ__get_N
int ImagoQ__get_N(MASH::RcppR6::RcppR6<MASH::ImagoQ> obj_);
RcppExport SEXP _MASH_ImagoQ__get_N(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::ImagoQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(ImagoQ__get_N(obj_));
    return rcpp_result_gen;
END_RCPP
}
// ImagoQ__set_N
void ImagoQ__set_N(MASH::RcppR6::RcppR6<MASH::ImagoQ> obj_, int N_new);
RcppExport SEXP _MASH_ImagoQ__set_N(SEXP obj_SEXP, SEXP N_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::ImagoQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type N_new(N_newSEXP);
    ImagoQ__set_N(obj_, N_new);
    return R_NilValue;
END_RCPP
}
// ImagoQ__get_ImagoQ
Rcpp::List ImagoQ__get_ImagoQ(MASH::RcppR6::RcppR6<MASH::ImagoQ> obj_);
RcppExport SEXP _MASH_ImagoQ__get_ImagoQ(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::ImagoQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(ImagoQ__get_ImagoQ(obj_));
    return rcpp_result_gen;
END_RCPP
}
// ImagoQ__get_ImagoQTime
Rcpp::List ImagoQ__get_ImagoQTime(MASH::RcppR6::RcppR6<MASH::ImagoQ> obj_, double tNow, bool clear);
RcppExport SEXP _MASH_ImagoQ__get_ImagoQTime(SEXP obj_SEXP, SEXP tNowSEXP, SEXP clearSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::ImagoQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type tNow(tNowSEXP);
    Rcpp::traits::input_parameter< bool >::type clear(clearSEXP);
    rcpp_result_gen = Rcpp::wrap(ImagoQ__get_ImagoQTime(obj_, tNow, clear));
    return rcpp_result_gen;
END_RCPP
}
// EggQ__ctor
MASH::EggQ EggQ__ctor();
RcppExport SEXP _MASH_EggQ__ctor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(EggQ__ctor());
    return rcpp_result_gen;
END_RCPP
}
// EggQ__clear_EggQ
void EggQ__clear_EggQ(MASH::RcppR6::RcppR6<MASH::EggQ> obj_);
RcppExport SEXP _MASH_EggQ__clear_EggQ(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EggQ> >::type obj_(obj_SEXP);
    EggQ__clear_EggQ(obj_);
    return R_NilValue;
END_RCPP
}
// EggQ__clear_EggQTime
void EggQ__clear_EggQTime(MASH::RcppR6::RcppR6<MASH::EggQ> obj_, double time);
RcppExport SEXP _MASH_EggQ__clear_EggQTime(SEXP obj_SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EggQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    EggQ__clear_EggQTime(obj_, time);
    return R_NilValue;
END_RCPP
}
// EggQ__add_EggQ
void EggQ__add_EggQ(MASH::RcppR6::RcppR6<MASH::EggQ> obj_, int N_new, double tOviposit_new, int genotype_new, std::string damID_new, std::string sireID_new);
RcppExport SEXP _MASH_EggQ__add_EggQ(SEXP obj_SEXP, SEXP N_newSEXP, SEXP tOviposit_newSEXP, SEXP genotype_newSEXP, SEXP damID_newSEXP, SEXP sireID_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EggQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type N_new(N_newSEXP);
    Rcpp::traits::input_parameter< double >::type tOviposit_new(tOviposit_newSEXP);
    Rcpp::traits::input_parameter< int >::type genotype_new(genotype_newSEXP);
    Rcpp::traits::input_parameter< std::string >::type damID_new(damID_newSEXP);
    Rcpp::traits::input_parameter< std::string >::type sireID_new(sireID_newSEXP);
    EggQ__add_EggQ(obj_, N_new, tOviposit_new, genotype_new, damID_new, sireID_new);
    return R_NilValue;
END_RCPP
}
// EggQ__track_EggQ
double EggQ__track_EggQ(MASH::RcppR6::RcppR6<MASH::EggQ> obj_, double time);
RcppExport SEXP _MASH_EggQ__track_EggQ(SEXP obj_SEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EggQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(EggQ__track_EggQ(obj_, time));
    return rcpp_result_gen;
END_RCPP
}
// EggQ__get_N
int EggQ__get_N(MASH::RcppR6::RcppR6<MASH::EggQ> obj_);
RcppExport SEXP _MASH_EggQ__get_N(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EggQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(EggQ__get_N(obj_));
    return rcpp_result_gen;
END_RCPP
}
// EggQ__set_N
void EggQ__set_N(MASH::RcppR6::RcppR6<MASH::EggQ> obj_, int N_new);
RcppExport SEXP _MASH_EggQ__set_N(SEXP obj_SEXP, SEXP N_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EggQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type N_new(N_newSEXP);
    EggQ__set_N(obj_, N_new);
    return R_NilValue;
END_RCPP
}
// EggQ__get_EggQ
Rcpp::List EggQ__get_EggQ(MASH::RcppR6::RcppR6<MASH::EggQ> obj_);
RcppExport SEXP _MASH_EggQ__get_EggQ(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EggQ> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(EggQ__get_EggQ(obj_));
    return rcpp_result_gen;
END_RCPP
}
// EggQ__get_EggQTime
Rcpp::List EggQ__get_EggQTime(MASH::RcppR6::RcppR6<MASH::EggQ> obj_, double tNow, bool clear);
RcppExport SEXP _MASH_EggQ__get_EggQTime(SEXP obj_SEXP, SEXP tNowSEXP, SEXP clearSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EggQ> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type tNow(tNowSEXP);
    Rcpp::traits::input_parameter< bool >::type clear(clearSEXP);
    rcpp_result_gen = Rcpp::wrap(EggQ__get_EggQTime(obj_, tNow, clear));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__ctor
MASH::EL4P EL4P__ctor(int numGenotypes, double psi_new, double alpha_new, double p_new);
RcppExport SEXP _MASH_EL4P__ctor(SEXP numGenotypesSEXP, SEXP psi_newSEXP, SEXP alpha_newSEXP, SEXP p_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type numGenotypes(numGenotypesSEXP);
    Rcpp::traits::input_parameter< double >::type psi_new(psi_newSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_new(alpha_newSEXP);
    Rcpp::traits::input_parameter< double >::type p_new(p_newSEXP);
    rcpp_result_gen = Rcpp::wrap(EL4P__ctor(numGenotypes, psi_new, alpha_new, p_new));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__oneStep
void EL4P__oneStep(MASH::RcppR6::RcppR6<MASH::EL4P> obj_);
RcppExport SEXP _MASH_EL4P__oneStep(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    EL4P__oneStep(obj_);
    return R_NilValue;
END_RCPP
}
// EL4P__oneStep_GEL4P
void EL4P__oneStep_GEL4P(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, double M, double eqAqua, double G, double lifespan);
RcppExport SEXP _MASH_EL4P__oneStep_GEL4P(SEXP obj_SEXP, SEXP MSEXP, SEXP eqAquaSEXP, SEXP GSEXP, SEXP lifespanSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type eqAqua(eqAquaSEXP);
    Rcpp::traits::input_parameter< double >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type lifespan(lifespanSEXP);
    EL4P__oneStep_GEL4P(obj_, M, eqAqua, G, lifespan);
    return R_NilValue;
END_RCPP
}
// EL4P__burnIn_GEL4P
void EL4P__burnIn_GEL4P(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, double M, double eqAqua, double G, double lifespan, int tMax);
RcppExport SEXP _MASH_EL4P__burnIn_GEL4P(SEXP obj_SEXP, SEXP MSEXP, SEXP eqAquaSEXP, SEXP GSEXP, SEXP lifespanSEXP, SEXP tMaxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type eqAqua(eqAquaSEXP);
    Rcpp::traits::input_parameter< double >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type lifespan(lifespanSEXP);
    Rcpp::traits::input_parameter< int >::type tMax(tMaxSEXP);
    EL4P__burnIn_GEL4P(obj_, M, eqAqua, G, lifespan, tMax);
    return R_NilValue;
END_RCPP
}
// EL4P__G2K_GEL4P
void EL4P__G2K_GEL4P(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, double eqAqua, double G, double lifespan, int tMax);
RcppExport SEXP _MASH_EL4P__G2K_GEL4P(SEXP obj_SEXP, SEXP eqAquaSEXP, SEXP GSEXP, SEXP lifespanSEXP, SEXP tMaxSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type eqAqua(eqAquaSEXP);
    Rcpp::traits::input_parameter< double >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type lifespan(lifespanSEXP);
    Rcpp::traits::input_parameter< int >::type tMax(tMaxSEXP);
    EL4P__G2K_GEL4P(obj_, eqAqua, G, lifespan, tMax);
    return R_NilValue;
END_RCPP
}
// EL4P__checkDX_GEL4P
std::vector<double> EL4P__checkDX_GEL4P(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, double eqAqua, double G, double lifespan, int tMax);
RcppExport SEXP _MASH_EL4P__checkDX_GEL4P(SEXP obj_SEXP, SEXP eqAquaSEXP, SEXP GSEXP, SEXP lifespanSEXP, SEXP tMaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type eqAqua(eqAquaSEXP);
    Rcpp::traits::input_parameter< double >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type lifespan(lifespanSEXP);
    Rcpp::traits::input_parameter< int >::type tMax(tMaxSEXP);
    rcpp_result_gen = Rcpp::wrap(EL4P__checkDX_GEL4P(obj_, eqAqua, G, lifespan, tMax));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__addEggs
void EL4P__addEggs(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, double eggs_N, int genotype);
RcppExport SEXP _MASH_EL4P__addEggs(SEXP obj_SEXP, SEXP eggs_NSEXP, SEXP genotypeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type eggs_N(eggs_NSEXP);
    Rcpp::traits::input_parameter< int >::type genotype(genotypeSEXP);
    EL4P__addEggs(obj_, eggs_N, genotype);
    return R_NilValue;
END_RCPP
}
// EL4P__get_allGenotypes
Rcpp::List EL4P__get_allGenotypes(MASH::RcppR6::RcppR6<MASH::EL4P> obj_);
RcppExport SEXP _MASH_EL4P__get_allGenotypes(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(EL4P__get_allGenotypes(obj_));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__get_genotypeIx
Rcpp::List EL4P__get_genotypeIx(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, int ix);
RcppExport SEXP _MASH_EL4P__get_genotypeIx(SEXP obj_SEXP, SEXP ixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type ix(ixSEXP);
    rcpp_result_gen = Rcpp::wrap(EL4P__get_genotypeIx(obj_, ix));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__get_psi
double EL4P__get_psi(MASH::RcppR6::RcppR6<MASH::EL4P> obj_);
RcppExport SEXP _MASH_EL4P__get_psi(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(EL4P__get_psi(obj_));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__set_psi
void EL4P__set_psi(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, double psi_new);
RcppExport SEXP _MASH_EL4P__set_psi(SEXP obj_SEXP, SEXP psi_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type psi_new(psi_newSEXP);
    EL4P__set_psi(obj_, psi_new);
    return R_NilValue;
END_RCPP
}
// EL4P__get_alpha
double EL4P__get_alpha(MASH::RcppR6::RcppR6<MASH::EL4P> obj_);
RcppExport SEXP _MASH_EL4P__get_alpha(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(EL4P__get_alpha(obj_));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__set_alpha
void EL4P__set_alpha(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, double alpha_new);
RcppExport SEXP _MASH_EL4P__set_alpha(SEXP obj_SEXP, SEXP alpha_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type alpha_new(alpha_newSEXP);
    EL4P__set_alpha(obj_, alpha_new);
    return R_NilValue;
END_RCPP
}
// EL4P__get_p
double EL4P__get_p(MASH::RcppR6::RcppR6<MASH::EL4P> obj_);
RcppExport SEXP _MASH_EL4P__get_p(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(EL4P__get_p(obj_));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__set_p
void EL4P__set_p(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, double p_new);
RcppExport SEXP _MASH_EL4P__set_p(SEXP obj_SEXP, SEXP p_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< double >::type p_new(p_newSEXP);
    EL4P__set_p(obj_, p_new);
    return R_NilValue;
END_RCPP
}
// EL4P__get_numGenotypes
int EL4P__get_numGenotypes(MASH::RcppR6::RcppR6<MASH::EL4P> obj_);
RcppExport SEXP _MASH_EL4P__get_numGenotypes(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(EL4P__get_numGenotypes(obj_));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__get_totalLambda
double EL4P__get_totalLambda(MASH::RcppR6::RcppR6<MASH::EL4P> obj_);
RcppExport SEXP _MASH_EL4P__get_totalLambda(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(EL4P__get_totalLambda(obj_));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__get_specificLambda
double EL4P__get_specificLambda(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, int ix);
RcppExport SEXP _MASH_EL4P__get_specificLambda(SEXP obj_SEXP, SEXP ixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< int >::type ix(ixSEXP);
    rcpp_result_gen = Rcpp::wrap(EL4P__get_specificLambda(obj_, ix));
    return rcpp_result_gen;
END_RCPP
}
// EL4P__reset
void EL4P__reset(MASH::RcppR6::RcppR6<MASH::EL4P> obj_);
RcppExport SEXP _MASH_EL4P__reset(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    EL4P__reset(obj_);
    return R_NilValue;
END_RCPP
}
// EL4P__set_pop
void EL4P__set_pop(MASH::RcppR6::RcppR6<MASH::EL4P> obj_, Rcpp::List initPop);
RcppExport SEXP _MASH_EL4P__set_pop(SEXP obj_SEXP, SEXP initPopSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::EL4P> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type initPop(initPopSEXP);
    EL4P__set_pop(obj_, initPop);
    return R_NilValue;
END_RCPP
}
// MosquitoFemaleHistory__ctor
MASH::MosquitoFemaleHistory MosquitoFemaleHistory__ctor();
RcppExport SEXP _MASH_MosquitoFemaleHistory__ctor() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(MosquitoFemaleHistory__ctor());
    return rcpp_result_gen;
END_RCPP
}
// MosquitoFemaleHistory__historyInit
void MosquitoFemaleHistory__historyInit(MASH::RcppR6::RcppR6<MASH::MosquitoFemaleHistory> obj_, Rcpp::Environment privateEnv);
RcppExport SEXP _MASH_MosquitoFemaleHistory__historyInit(SEXP obj_SEXP, SEXP privateEnvSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::MosquitoFemaleHistory> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment >::type privateEnv(privateEnvSEXP);
    MosquitoFemaleHistory__historyInit(obj_, privateEnv);
    return R_NilValue;
END_RCPP
}
// MosquitoFemaleHistory__historyTrack
void MosquitoFemaleHistory__historyTrack(MASH::RcppR6::RcppR6<MASH::MosquitoFemaleHistory> obj_, Rcpp::Environment privateEnv, bool alive);
RcppExport SEXP _MASH_MosquitoFemaleHistory__historyTrack(SEXP obj_SEXP, SEXP privateEnvSEXP, SEXP aliveSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::MosquitoFemaleHistory> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment >::type privateEnv(privateEnvSEXP);
    Rcpp::traits::input_parameter< bool >::type alive(aliveSEXP);
    MosquitoFemaleHistory__historyTrack(obj_, privateEnv, alive);
    return R_NilValue;
END_RCPP
}
// MosquitoFemaleHistory__historyFeed
void MosquitoFemaleHistory__historyFeed(MASH::RcppR6::RcppR6<MASH::MosquitoFemaleHistory> obj_, Rcpp::Environment privateEnv);
RcppExport SEXP _MASH_MosquitoFemaleHistory__historyFeed(SEXP obj_SEXP, SEXP privateEnvSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::MosquitoFemaleHistory> >::type obj_(obj_SEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment >::type privateEnv(privateEnvSEXP);
    MosquitoFemaleHistory__historyFeed(obj_, privateEnv);
    return R_NilValue;
END_RCPP
}
// MosquitoFemaleHistory__calcBionomics
void MosquitoFemaleHistory__calcBionomics(MASH::RcppR6::RcppR6<MASH::MosquitoFemaleHistory> obj_);
RcppExport SEXP _MASH_MosquitoFemaleHistory__calcBionomics(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::MosquitoFemaleHistory> >::type obj_(obj_SEXP);
    MosquitoFemaleHistory__calcBionomics(obj_);
    return R_NilValue;
END_RCPP
}
// MosquitoFemaleHistory__exportHistory
Rcpp::List MosquitoFemaleHistory__exportHistory(MASH::RcppR6::RcppR6<MASH::MosquitoFemaleHistory> obj_);
RcppExport SEXP _MASH_MosquitoFemaleHistory__exportHistory(SEXP obj_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< MASH::RcppR6::RcppR6<MASH::MosquitoFemaleHistory> >::type obj_(obj_SEXP);
    rcpp_result_gen = Rcpp::wrap(MosquitoFemaleHistory__exportHistory(obj_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MASH_util_PfSIoneHistory", (DL_FUNC) &_MASH_util_PfSIoneHistory, 3},
    {"_MASH_HumanEventQ__ctor", (DL_FUNC) &_MASH_HumanEventQ__ctor, 1},
    {"_MASH_HumanEventQ__firstEvent", (DL_FUNC) &_MASH_HumanEventQ__firstEvent, 1},
    {"_MASH_HumanEventQ__firstTime", (DL_FUNC) &_MASH_HumanEventQ__firstTime, 1},
    {"_MASH_HumanEventQ__rmFirstEventFromQ", (DL_FUNC) &_MASH_HumanEventQ__rmFirstEventFromQ, 1},
    {"_MASH_HumanEventQ__rmTagFromQ", (DL_FUNC) &_MASH_HumanEventQ__rmTagFromQ, 2},
    {"_MASH_HumanEventQ__get_queueN", (DL_FUNC) &_MASH_HumanEventQ__get_queueN, 1},
    {"_MASH_HumanEventQ__addEvent2Q", (DL_FUNC) &_MASH_HumanEventQ__addEvent2Q, 2},
    {"_MASH_HumanEventQ__get_EventQ", (DL_FUNC) &_MASH_HumanEventQ__get_EventQ, 1},
    {"_MASH_HistoryGeneric__ctor", (DL_FUNC) &_MASH_HistoryGeneric__ctor, 1},
    {"_MASH_HistoryGeneric__track_history", (DL_FUNC) &_MASH_HistoryGeneric__track_history, 3},
    {"_MASH_HistoryGeneric__get_history", (DL_FUNC) &_MASH_HistoryGeneric__get_history, 1},
    {"_MASH_HistoryTravel__ctor", (DL_FUNC) &_MASH_HistoryTravel__ctor, 1},
    {"_MASH_HistoryTravel__track_travel", (DL_FUNC) &_MASH_HistoryTravel__track_travel, 3},
    {"_MASH_HistoryTravel__get_travelHistory", (DL_FUNC) &_MASH_HistoryTravel__get_travelHistory, 1},
    {"_MASH_humanPfSI__ctor", (DL_FUNC) &_MASH_humanPfSI__ctor, 8},
    {"_MASH_humanPfSI__get_PfID", (DL_FUNC) &_MASH_humanPfSI__get_PfID, 1},
    {"_MASH_humanPfSI__push_PfID", (DL_FUNC) &_MASH_humanPfSI__push_PfID, 2},
    {"_MASH_humanPfSI__back_PfID", (DL_FUNC) &_MASH_humanPfSI__back_PfID, 1},
    {"_MASH_humanPfSI__get_tInf", (DL_FUNC) &_MASH_humanPfSI__get_tInf, 1},
    {"_MASH_humanPfSI__push_tInf", (DL_FUNC) &_MASH_humanPfSI__push_tInf, 2},
    {"_MASH_humanPfSI__get_b", (DL_FUNC) &_MASH_humanPfSI__get_b, 1},
    {"_MASH_humanPfSI__set_b", (DL_FUNC) &_MASH_humanPfSI__set_b, 2},
    {"_MASH_humanPfSI__get_c", (DL_FUNC) &_MASH_humanPfSI__get_c, 1},
    {"_MASH_humanPfSI__set_c", (DL_FUNC) &_MASH_humanPfSI__set_c, 2},
    {"_MASH_humanPfSI__get_damID", (DL_FUNC) &_MASH_humanPfSI__get_damID, 1},
    {"_MASH_humanPfSI__push_damID", (DL_FUNC) &_MASH_humanPfSI__push_damID, 2},
    {"_MASH_humanPfSI__get_sireID", (DL_FUNC) &_MASH_humanPfSI__get_sireID, 1},
    {"_MASH_humanPfSI__push_sireID", (DL_FUNC) &_MASH_humanPfSI__push_sireID, 2},
    {"_MASH_humanPfSI__get_infected", (DL_FUNC) &_MASH_humanPfSI__get_infected, 1},
    {"_MASH_humanPfSI__set_infected", (DL_FUNC) &_MASH_humanPfSI__set_infected, 2},
    {"_MASH_humanPfSI__get_chemoprophylaxis", (DL_FUNC) &_MASH_humanPfSI__get_chemoprophylaxis, 1},
    {"_MASH_humanPfSI__set_chemoprophylaxis", (DL_FUNC) &_MASH_humanPfSI__set_chemoprophylaxis, 2},
    {"_MASH_humanPfSI__track_history", (DL_FUNC) &_MASH_humanPfSI__track_history, 3},
    {"_MASH_humanPfSI__get_history", (DL_FUNC) &_MASH_humanPfSI__get_history, 1},
    {"_MASH_mosquitoPfSI__ctor", (DL_FUNC) &_MASH_mosquitoPfSI__ctor, 5},
    {"_MASH_mosquitoPfSI__get_PfID", (DL_FUNC) &_MASH_mosquitoPfSI__get_PfID, 1},
    {"_MASH_mosquitoPfSI__set_PfID", (DL_FUNC) &_MASH_mosquitoPfSI__set_PfID, 2},
    {"_MASH_mosquitoPfSI__get_tInf", (DL_FUNC) &_MASH_mosquitoPfSI__get_tInf, 1},
    {"_MASH_mosquitoPfSI__set_tInf", (DL_FUNC) &_MASH_mosquitoPfSI__set_tInf, 2},
    {"_MASH_mosquitoPfSI__get_damID", (DL_FUNC) &_MASH_mosquitoPfSI__get_damID, 1},
    {"_MASH_mosquitoPfSI__set_damID", (DL_FUNC) &_MASH_mosquitoPfSI__set_damID, 2},
    {"_MASH_mosquitoPfSI__get_sireID", (DL_FUNC) &_MASH_mosquitoPfSI__get_sireID, 1},
    {"_MASH_mosquitoPfSI__set_sireID", (DL_FUNC) &_MASH_mosquitoPfSI__set_sireID, 2},
    {"_MASH_mosquitoPfSI__get_infected", (DL_FUNC) &_MASH_mosquitoPfSI__get_infected, 1},
    {"_MASH_mosquitoPfSI__set_infected", (DL_FUNC) &_MASH_mosquitoPfSI__set_infected, 2},
    {"_MASH_humanPfMOI__ctor", (DL_FUNC) &_MASH_humanPfMOI__ctor, 8},
    {"_MASH_humanPfMOI__get_PfID", (DL_FUNC) &_MASH_humanPfMOI__get_PfID, 1},
    {"_MASH_humanPfMOI__push_PfID", (DL_FUNC) &_MASH_humanPfMOI__push_PfID, 2},
    {"_MASH_humanPfMOI__get_tInf", (DL_FUNC) &_MASH_humanPfMOI__get_tInf, 1},
    {"_MASH_humanPfMOI__push_tInf", (DL_FUNC) &_MASH_humanPfMOI__push_tInf, 2},
    {"_MASH_humanPfMOI__get_MOI", (DL_FUNC) &_MASH_humanPfMOI__get_MOI, 1},
    {"_MASH_humanPfMOI__set_MOI", (DL_FUNC) &_MASH_humanPfMOI__set_MOI, 2},
    {"_MASH_humanPfMOI__get_b", (DL_FUNC) &_MASH_humanPfMOI__get_b, 1},
    {"_MASH_humanPfMOI__set_b", (DL_FUNC) &_MASH_humanPfMOI__set_b, 2},
    {"_MASH_humanPfMOI__get_c", (DL_FUNC) &_MASH_humanPfMOI__get_c, 1},
    {"_MASH_humanPfMOI__set_c", (DL_FUNC) &_MASH_humanPfMOI__set_c, 2},
    {"_MASH_humanPfMOI__get_damID", (DL_FUNC) &_MASH_humanPfMOI__get_damID, 1},
    {"_MASH_humanPfMOI__push_damID", (DL_FUNC) &_MASH_humanPfMOI__push_damID, 2},
    {"_MASH_humanPfMOI__get_sireID", (DL_FUNC) &_MASH_humanPfMOI__get_sireID, 1},
    {"_MASH_humanPfMOI__push_sireID", (DL_FUNC) &_MASH_humanPfMOI__push_sireID, 2},
    {"_MASH_humanPfMOI__get_chemoprophylaxis", (DL_FUNC) &_MASH_humanPfMOI__get_chemoprophylaxis, 1},
    {"_MASH_humanPfMOI__set_chemoprophylaxis", (DL_FUNC) &_MASH_humanPfMOI__set_chemoprophylaxis, 2},
    {"_MASH_humanPfMOI__add_Infection", (DL_FUNC) &_MASH_humanPfMOI__add_Infection, 4},
    {"_MASH_humanPfMOI__clear_Infection", (DL_FUNC) &_MASH_humanPfMOI__clear_Infection, 2},
    {"_MASH_humanPfMOI__get_Infection", (DL_FUNC) &_MASH_humanPfMOI__get_Infection, 1},
    {"_MASH_humanPfMOI__track_history", (DL_FUNC) &_MASH_humanPfMOI__track_history, 3},
    {"_MASH_humanPfMOI__get_history", (DL_FUNC) &_MASH_humanPfMOI__get_history, 1},
    {"_MASH_mosquitoPfMOI__ctor", (DL_FUNC) &_MASH_mosquitoPfMOI__ctor, 5},
    {"_MASH_mosquitoPfMOI__get_PfID", (DL_FUNC) &_MASH_mosquitoPfMOI__get_PfID, 1},
    {"_MASH_mosquitoPfMOI__push_PfID", (DL_FUNC) &_MASH_mosquitoPfMOI__push_PfID, 2},
    {"_MASH_mosquitoPfMOI__get_tInf", (DL_FUNC) &_MASH_mosquitoPfMOI__get_tInf, 1},
    {"_MASH_mosquitoPfMOI__push_tInf", (DL_FUNC) &_MASH_mosquitoPfMOI__push_tInf, 2},
    {"_MASH_mosquitoPfMOI__get_MOI", (DL_FUNC) &_MASH_mosquitoPfMOI__get_MOI, 1},
    {"_MASH_mosquitoPfMOI__set_MOI", (DL_FUNC) &_MASH_mosquitoPfMOI__set_MOI, 2},
    {"_MASH_mosquitoPfMOI__get_damID", (DL_FUNC) &_MASH_mosquitoPfMOI__get_damID, 1},
    {"_MASH_mosquitoPfMOI__push_damID", (DL_FUNC) &_MASH_mosquitoPfMOI__push_damID, 2},
    {"_MASH_mosquitoPfMOI__get_sireID", (DL_FUNC) &_MASH_mosquitoPfMOI__get_sireID, 1},
    {"_MASH_mosquitoPfMOI__push_sireID", (DL_FUNC) &_MASH_mosquitoPfMOI__push_sireID, 2},
    {"_MASH_mosquitoPfMOI__add_Infection", (DL_FUNC) &_MASH_mosquitoPfMOI__add_Infection, 5},
    {"_MASH_mosquitoPfMOI__get_Infection", (DL_FUNC) &_MASH_mosquitoPfMOI__get_Infection, 2},
    {"_MASH_mosquitoPfMOI__get_InfectionIx", (DL_FUNC) &_MASH_mosquitoPfMOI__get_InfectionIx, 2},
    {"_MASH_mosquitoPfMOI__get_InfectionEIP", (DL_FUNC) &_MASH_mosquitoPfMOI__get_InfectionEIP, 2},
    {"_MASH_mosquitoPfMOI__which_EIP", (DL_FUNC) &_MASH_mosquitoPfMOI__which_EIP, 2},
    {"_MASH_RiskQ__ctor", (DL_FUNC) &_MASH_RiskQ__ctor, 0},
    {"_MASH_RiskQ__get_N", (DL_FUNC) &_MASH_RiskQ__get_N, 1},
    {"_MASH_RiskQ__set_N", (DL_FUNC) &_MASH_RiskQ__set_N, 2},
    {"_MASH_RiskQ__get_who", (DL_FUNC) &_MASH_RiskQ__get_who, 1},
    {"_MASH_RiskQ__push_who", (DL_FUNC) &_MASH_RiskQ__push_who, 2},
    {"_MASH_RiskQ__get_pTm", (DL_FUNC) &_MASH_RiskQ__get_pTm, 1},
    {"_MASH_RiskQ__push_pTm", (DL_FUNC) &_MASH_RiskQ__push_pTm, 2},
    {"_MASH_RiskQ__get_w", (DL_FUNC) &_MASH_RiskQ__get_w, 1},
    {"_MASH_RiskQ__push_w", (DL_FUNC) &_MASH_RiskQ__push_w, 2},
    {"_MASH_RiskQ__add_HumanHost", (DL_FUNC) &_MASH_RiskQ__add_HumanHost, 4},
    {"_MASH_RiskQ__get_HumanHost", (DL_FUNC) &_MASH_RiskQ__get_HumanHost, 1},
    {"_MASH_RiskQ__get_HumanHostIx", (DL_FUNC) &_MASH_RiskQ__get_HumanHostIx, 2},
    {"_MASH_RiskQ__clear_HumanHost", (DL_FUNC) &_MASH_RiskQ__clear_HumanHost, 1},
    {"_MASH_RiskQ__get_nOther", (DL_FUNC) &_MASH_RiskQ__get_nOther, 1},
    {"_MASH_RiskQ__set_nOther", (DL_FUNC) &_MASH_RiskQ__set_nOther, 2},
    {"_MASH_RiskQ__add_OtherHost", (DL_FUNC) &_MASH_RiskQ__add_OtherHost, 3},
    {"_MASH_RiskQ__get_OtherHost", (DL_FUNC) &_MASH_RiskQ__get_OtherHost, 1},
    {"_MASH_ImagoQ__ctor", (DL_FUNC) &_MASH_ImagoQ__ctor, 0},
    {"_MASH_ImagoQ__clear_ImagoQ", (DL_FUNC) &_MASH_ImagoQ__clear_ImagoQ, 1},
    {"_MASH_ImagoQ__clear_ImagoQTime", (DL_FUNC) &_MASH_ImagoQ__clear_ImagoQTime, 2},
    {"_MASH_ImagoQ__add_ImagoQ", (DL_FUNC) &_MASH_ImagoQ__add_ImagoQ, 6},
    {"_MASH_ImagoQ__track_ImagoQ", (DL_FUNC) &_MASH_ImagoQ__track_ImagoQ, 2},
    {"_MASH_ImagoQ__get_N", (DL_FUNC) &_MASH_ImagoQ__get_N, 1},
    {"_MASH_ImagoQ__set_N", (DL_FUNC) &_MASH_ImagoQ__set_N, 2},
    {"_MASH_ImagoQ__get_ImagoQ", (DL_FUNC) &_MASH_ImagoQ__get_ImagoQ, 1},
    {"_MASH_ImagoQ__get_ImagoQTime", (DL_FUNC) &_MASH_ImagoQ__get_ImagoQTime, 3},
    {"_MASH_EggQ__ctor", (DL_FUNC) &_MASH_EggQ__ctor, 0},
    {"_MASH_EggQ__clear_EggQ", (DL_FUNC) &_MASH_EggQ__clear_EggQ, 1},
    {"_MASH_EggQ__clear_EggQTime", (DL_FUNC) &_MASH_EggQ__clear_EggQTime, 2},
    {"_MASH_EggQ__add_EggQ", (DL_FUNC) &_MASH_EggQ__add_EggQ, 6},
    {"_MASH_EggQ__track_EggQ", (DL_FUNC) &_MASH_EggQ__track_EggQ, 2},
    {"_MASH_EggQ__get_N", (DL_FUNC) &_MASH_EggQ__get_N, 1},
    {"_MASH_EggQ__set_N", (DL_FUNC) &_MASH_EggQ__set_N, 2},
    {"_MASH_EggQ__get_EggQ", (DL_FUNC) &_MASH_EggQ__get_EggQ, 1},
    {"_MASH_EggQ__get_EggQTime", (DL_FUNC) &_MASH_EggQ__get_EggQTime, 3},
    {"_MASH_EL4P__ctor", (DL_FUNC) &_MASH_EL4P__ctor, 4},
    {"_MASH_EL4P__oneStep", (DL_FUNC) &_MASH_EL4P__oneStep, 1},
    {"_MASH_EL4P__oneStep_GEL4P", (DL_FUNC) &_MASH_EL4P__oneStep_GEL4P, 5},
    {"_MASH_EL4P__burnIn_GEL4P", (DL_FUNC) &_MASH_EL4P__burnIn_GEL4P, 6},
    {"_MASH_EL4P__G2K_GEL4P", (DL_FUNC) &_MASH_EL4P__G2K_GEL4P, 5},
    {"_MASH_EL4P__checkDX_GEL4P", (DL_FUNC) &_MASH_EL4P__checkDX_GEL4P, 5},
    {"_MASH_EL4P__addEggs", (DL_FUNC) &_MASH_EL4P__addEggs, 3},
    {"_MASH_EL4P__get_allGenotypes", (DL_FUNC) &_MASH_EL4P__get_allGenotypes, 1},
    {"_MASH_EL4P__get_genotypeIx", (DL_FUNC) &_MASH_EL4P__get_genotypeIx, 2},
    {"_MASH_EL4P__get_psi", (DL_FUNC) &_MASH_EL4P__get_psi, 1},
    {"_MASH_EL4P__set_psi", (DL_FUNC) &_MASH_EL4P__set_psi, 2},
    {"_MASH_EL4P__get_alpha", (DL_FUNC) &_MASH_EL4P__get_alpha, 1},
    {"_MASH_EL4P__set_alpha", (DL_FUNC) &_MASH_EL4P__set_alpha, 2},
    {"_MASH_EL4P__get_p", (DL_FUNC) &_MASH_EL4P__get_p, 1},
    {"_MASH_EL4P__set_p", (DL_FUNC) &_MASH_EL4P__set_p, 2},
    {"_MASH_EL4P__get_numGenotypes", (DL_FUNC) &_MASH_EL4P__get_numGenotypes, 1},
    {"_MASH_EL4P__get_totalLambda", (DL_FUNC) &_MASH_EL4P__get_totalLambda, 1},
    {"_MASH_EL4P__get_specificLambda", (DL_FUNC) &_MASH_EL4P__get_specificLambda, 2},
    {"_MASH_EL4P__reset", (DL_FUNC) &_MASH_EL4P__reset, 1},
    {"_MASH_EL4P__set_pop", (DL_FUNC) &_MASH_EL4P__set_pop, 2},
    {"_MASH_MosquitoFemaleHistory__ctor", (DL_FUNC) &_MASH_MosquitoFemaleHistory__ctor, 0},
    {"_MASH_MosquitoFemaleHistory__historyInit", (DL_FUNC) &_MASH_MosquitoFemaleHistory__historyInit, 2},
    {"_MASH_MosquitoFemaleHistory__historyTrack", (DL_FUNC) &_MASH_MosquitoFemaleHistory__historyTrack, 3},
    {"_MASH_MosquitoFemaleHistory__historyFeed", (DL_FUNC) &_MASH_MosquitoFemaleHistory__historyFeed, 2},
    {"_MASH_MosquitoFemaleHistory__calcBionomics", (DL_FUNC) &_MASH_MosquitoFemaleHistory__calcBionomics, 1},
    {"_MASH_MosquitoFemaleHistory__exportHistory", (DL_FUNC) &_MASH_MosquitoFemaleHistory__exportHistory, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MASH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
