ET = function(){
  TRB = (TB+PBF*PFB*TF)/(1-PBF*PFB)
  TRF = (TF+TB)/(1-PBF*PFB)
  TRO = (TO+POL*PLO*TL)/(1-POL*PLO)+POF/(POF+POB)*TRF+POB/(POF+POB)*TRB
  TRL = (TO+TL)/(1-POL*PLO)+POF/(POF+POB)*TRF+POB/(POF+POB)*TRB
  Ttot = PRB*TRB+PRF*TRF+PRO*TRO+PRL*TRL+TR
  return(Ttot)
}

PS = function(){
  PBR/(1-PBF*PFB)*(PRB+PRF*PFB+(PRO+PRL*PLO)*(POB+POF*PFB)/(1-POL*PLO))
}