# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_hello <- function() {
    .Call('_MASHcpp_rcpp_hello', PACKAGE = 'MASHcpp')
}

HumanEventQ__ctor <- function(initQ) {
    .Call('_MASHcpp_HumanEventQ__ctor', PACKAGE = 'MASHcpp', initQ)
}

HumanEventQ__firstEvent <- function(obj_) {
    .Call('_MASHcpp_HumanEventQ__firstEvent', PACKAGE = 'MASHcpp', obj_)
}

HumanEventQ__firstTime <- function(obj_) {
    .Call('_MASHcpp_HumanEventQ__firstTime', PACKAGE = 'MASHcpp', obj_)
}

HumanEventQ__rmFirstEventFromQ <- function(obj_) {
    invisible(.Call('_MASHcpp_HumanEventQ__rmFirstEventFromQ', PACKAGE = 'MASHcpp', obj_))
}

HumanEventQ__rmTagFromQ <- function(obj_, tag) {
    invisible(.Call('_MASHcpp_HumanEventQ__rmTagFromQ', PACKAGE = 'MASHcpp', obj_, tag))
}

HumanEventQ__get_queueN <- function(obj_) {
    .Call('_MASHcpp_HumanEventQ__get_queueN', PACKAGE = 'MASHcpp', obj_)
}

HumanEventQ__addEvent2Q <- function(obj_, event) {
    invisible(.Call('_MASHcpp_HumanEventQ__addEvent2Q', PACKAGE = 'MASHcpp', obj_, event))
}

HumanEventQ__get_EventQ <- function(obj_) {
    .Call('_MASHcpp_HumanEventQ__get_EventQ', PACKAGE = 'MASHcpp', obj_)
}

HumanEventQ__clearQ <- function(obj_) {
    invisible(.Call('_MASHcpp_HumanEventQ__clearQ', PACKAGE = 'MASHcpp', obj_))
}

HistoryGeneric__ctor <- function(N) {
    .Call('_MASHcpp_HistoryGeneric__ctor', PACKAGE = 'MASHcpp', N)
}

HistoryGeneric__track_history <- function(obj_, tEvent, event) {
    invisible(.Call('_MASHcpp_HistoryGeneric__track_history', PACKAGE = 'MASHcpp', obj_, tEvent, event))
}

HistoryGeneric__get_history <- function(obj_) {
    .Call('_MASHcpp_HistoryGeneric__get_history', PACKAGE = 'MASHcpp', obj_)
}

HistoryTravel__ctor <- function(N) {
    .Call('_MASHcpp_HistoryTravel__ctor', PACKAGE = 'MASHcpp', N)
}

HistoryTravel__track_travel <- function(obj_, tTravel, locationH) {
    invisible(.Call('_MASHcpp_HistoryTravel__track_travel', PACKAGE = 'MASHcpp', obj_, tTravel, locationH))
}

HistoryTravel__get_travelHistory <- function(obj_) {
    .Call('_MASHcpp_HistoryTravel__get_travelHistory', PACKAGE = 'MASHcpp', obj_)
}

humanPfSI__ctor <- function(PfID_init, tInf_init, b_init, c_init, infected_init, chemoprophylaxis_init, N) {
    .Call('_MASHcpp_humanPfSI__ctor', PACKAGE = 'MASHcpp', PfID_init, tInf_init, b_init, c_init, infected_init, chemoprophylaxis_init, N)
}

humanPfSI__get_PfID <- function(obj_) {
    .Call('_MASHcpp_humanPfSI__get_PfID', PACKAGE = 'MASHcpp', obj_)
}

humanPfSI__push_PfID <- function(obj_, PfID_new) {
    invisible(.Call('_MASHcpp_humanPfSI__push_PfID', PACKAGE = 'MASHcpp', obj_, PfID_new))
}

humanPfSI__back_PfID <- function(obj_) {
    .Call('_MASHcpp_humanPfSI__back_PfID', PACKAGE = 'MASHcpp', obj_)
}

humanPfSI__get_tInf <- function(obj_) {
    .Call('_MASHcpp_humanPfSI__get_tInf', PACKAGE = 'MASHcpp', obj_)
}

humanPfSI__push_tInf <- function(obj_, tInf_new) {
    invisible(.Call('_MASHcpp_humanPfSI__push_tInf', PACKAGE = 'MASHcpp', obj_, tInf_new))
}

humanPfSI__get_b <- function(obj_) {
    .Call('_MASHcpp_humanPfSI__get_b', PACKAGE = 'MASHcpp', obj_)
}

humanPfSI__set_b <- function(obj_, b_new) {
    invisible(.Call('_MASHcpp_humanPfSI__set_b', PACKAGE = 'MASHcpp', obj_, b_new))
}

humanPfSI__get_c <- function(obj_) {
    .Call('_MASHcpp_humanPfSI__get_c', PACKAGE = 'MASHcpp', obj_)
}

humanPfSI__set_c <- function(obj_, c_new) {
    invisible(.Call('_MASHcpp_humanPfSI__set_c', PACKAGE = 'MASHcpp', obj_, c_new))
}

humanPfSI__get_vectorInf <- function(obj_) {
    .Call('_MASHcpp_humanPfSI__get_vectorInf', PACKAGE = 'MASHcpp', obj_)
}

humanPfSI__push_vectorInf <- function(obj_, vectorInf_new) {
    invisible(.Call('_MASHcpp_humanPfSI__push_vectorInf', PACKAGE = 'MASHcpp', obj_, vectorInf_new))
}

humanPfSI__get_infected <- function(obj_) {
    .Call('_MASHcpp_humanPfSI__get_infected', PACKAGE = 'MASHcpp', obj_)
}

humanPfSI__set_infected <- function(obj_, infected_new) {
    invisible(.Call('_MASHcpp_humanPfSI__set_infected', PACKAGE = 'MASHcpp', obj_, infected_new))
}

humanPfSI__get_chemoprophylaxis <- function(obj_) {
    .Call('_MASHcpp_humanPfSI__get_chemoprophylaxis', PACKAGE = 'MASHcpp', obj_)
}

humanPfSI__set_chemoprophylaxis <- function(obj_, chemoprophylaxis_new) {
    invisible(.Call('_MASHcpp_humanPfSI__set_chemoprophylaxis', PACKAGE = 'MASHcpp', obj_, chemoprophylaxis_new))
}

humanPfSI__track_history <- function(obj_, tEvent, event) {
    invisible(.Call('_MASHcpp_humanPfSI__track_history', PACKAGE = 'MASHcpp', obj_, tEvent, event))
}

humanPfSI__get_history <- function(obj_) {
    .Call('_MASHcpp_humanPfSI__get_history', PACKAGE = 'MASHcpp', obj_)
}

mosquitoPfSI__ctor <- function(PfID_init, MosquitoID_init, tInf_init, infected_init) {
    .Call('_MASHcpp_mosquitoPfSI__ctor', PACKAGE = 'MASHcpp', PfID_init, MosquitoID_init, tInf_init, infected_init)
}

mosquitoPfSI__get_PfID <- function(obj_) {
    .Call('_MASHcpp_mosquitoPfSI__get_PfID', PACKAGE = 'MASHcpp', obj_)
}

mosquitoPfSI__set_PfID <- function(obj_, PfID_new) {
    invisible(.Call('_MASHcpp_mosquitoPfSI__set_PfID', PACKAGE = 'MASHcpp', obj_, PfID_new))
}

mosquitoPfSI__get_MosquitoID <- function(obj_) {
    .Call('_MASHcpp_mosquitoPfSI__get_MosquitoID', PACKAGE = 'MASHcpp', obj_)
}

mosquitoPfSI__set_MosquitoID <- function(obj_, MosquitoID_new) {
    invisible(.Call('_MASHcpp_mosquitoPfSI__set_MosquitoID', PACKAGE = 'MASHcpp', obj_, MosquitoID_new))
}

mosquitoPfSI__get_tInf <- function(obj_) {
    .Call('_MASHcpp_mosquitoPfSI__get_tInf', PACKAGE = 'MASHcpp', obj_)
}

mosquitoPfSI__set_tInf <- function(obj_, tInf_new) {
    invisible(.Call('_MASHcpp_mosquitoPfSI__set_tInf', PACKAGE = 'MASHcpp', obj_, tInf_new))
}

mosquitoPfSI__get_humanInf <- function(obj_) {
    .Call('_MASHcpp_mosquitoPfSI__get_humanInf', PACKAGE = 'MASHcpp', obj_)
}

mosquitoPfSI__set_humanInf <- function(obj_, humanInf_new) {
    invisible(.Call('_MASHcpp_mosquitoPfSI__set_humanInf', PACKAGE = 'MASHcpp', obj_, humanInf_new))
}

mosquitoPfSI__get_infected <- function(obj_) {
    .Call('_MASHcpp_mosquitoPfSI__get_infected', PACKAGE = 'MASHcpp', obj_)
}

mosquitoPfSI__set_infected <- function(obj_, infected_new) {
    invisible(.Call('_MASHcpp_mosquitoPfSI__set_infected', PACKAGE = 'MASHcpp', obj_, infected_new))
}

mosquitoPfSI__get_history <- function(obj_) {
    .Call('_MASHcpp_mosquitoPfSI__get_history', PACKAGE = 'MASHcpp', obj_)
}

humanPfMOI__ctor <- function(b_init, c_init, chemoprophylaxis_init) {
    .Call('_MASHcpp_humanPfMOI__ctor', PACKAGE = 'MASHcpp', b_init, c_init, chemoprophylaxis_init)
}

humanPfMOI__get_PfID <- function(obj_) {
    .Call('_MASHcpp_humanPfMOI__get_PfID', PACKAGE = 'MASHcpp', obj_)
}

humanPfMOI__get_tInf <- function(obj_) {
    .Call('_MASHcpp_humanPfMOI__get_tInf', PACKAGE = 'MASHcpp', obj_)
}

humanPfMOI__get_MOI <- function(obj_) {
    .Call('_MASHcpp_humanPfMOI__get_MOI', PACKAGE = 'MASHcpp', obj_)
}

humanPfMOI__get_b <- function(obj_) {
    .Call('_MASHcpp_humanPfMOI__get_b', PACKAGE = 'MASHcpp', obj_)
}

humanPfMOI__set_b <- function(obj_, b_new) {
    invisible(.Call('_MASHcpp_humanPfMOI__set_b', PACKAGE = 'MASHcpp', obj_, b_new))
}

humanPfMOI__get_c <- function(obj_) {
    .Call('_MASHcpp_humanPfMOI__get_c', PACKAGE = 'MASHcpp', obj_)
}

humanPfMOI__set_c <- function(obj_, c_new) {
    invisible(.Call('_MASHcpp_humanPfMOI__set_c', PACKAGE = 'MASHcpp', obj_, c_new))
}

humanPfMOI__get_chemoprophylaxis <- function(obj_) {
    .Call('_MASHcpp_humanPfMOI__get_chemoprophylaxis', PACKAGE = 'MASHcpp', obj_)
}

humanPfMOI__set_chemoprophylaxis <- function(obj_, chemoprophylaxis_new) {
    invisible(.Call('_MASHcpp_humanPfMOI__set_chemoprophylaxis', PACKAGE = 'MASHcpp', obj_, chemoprophylaxis_new))
}

humanPfMOI__add_Infection <- function(obj_, PfID_new, tInf_new) {
    invisible(.Call('_MASHcpp_humanPfMOI__add_Infection', PACKAGE = 'MASHcpp', obj_, PfID_new, tInf_new))
}

humanPfMOI__clear_Infection <- function(obj_, PfID_ix) {
    invisible(.Call('_MASHcpp_humanPfMOI__clear_Infection', PACKAGE = 'MASHcpp', obj_, PfID_ix))
}

humanPfMOI__clear_Infections <- function(obj_) {
    invisible(.Call('_MASHcpp_humanPfMOI__clear_Infections', PACKAGE = 'MASHcpp', obj_))
}

humanPfMOI__get_Infection <- function(obj_) {
    .Call('_MASHcpp_humanPfMOI__get_Infection', PACKAGE = 'MASHcpp', obj_)
}

mosquitoPfMOI__ctor <- function(MosquitoID_init) {
    .Call('_MASHcpp_mosquitoPfMOI__ctor', PACKAGE = 'MASHcpp', MosquitoID_init)
}

mosquitoPfMOI__get_PfID <- function(obj_) {
    .Call('_MASHcpp_mosquitoPfMOI__get_PfID', PACKAGE = 'MASHcpp', obj_)
}

mosquitoPfMOI__get_MOI <- function(obj_) {
    .Call('_MASHcpp_mosquitoPfMOI__get_MOI', PACKAGE = 'MASHcpp', obj_)
}

mosquitoPfMOI__add_infection <- function(obj_, PfID_new, tInfected_new, tInfectious_new) {
    invisible(.Call('_MASHcpp_mosquitoPfMOI__add_infection', PACKAGE = 'MASHcpp', obj_, PfID_new, tInfected_new, tInfectious_new))
}

mosquitoPfMOI__get_infections <- function(obj_, tNow) {
    .Call('_MASHcpp_mosquitoPfMOI__get_infections', PACKAGE = 'MASHcpp', obj_, tNow)
}

RiskQ__ctor <- function() {
    .Call('_MASHcpp_RiskQ__ctor', PACKAGE = 'MASHcpp')
}

RiskQ__get_N <- function(obj_) {
    .Call('_MASHcpp_RiskQ__get_N', PACKAGE = 'MASHcpp', obj_)
}

RiskQ__set_N <- function(obj_, N_new) {
    invisible(.Call('_MASHcpp_RiskQ__set_N', PACKAGE = 'MASHcpp', obj_, N_new))
}

RiskQ__get_who <- function(obj_) {
    .Call('_MASHcpp_RiskQ__get_who', PACKAGE = 'MASHcpp', obj_)
}

RiskQ__push_who <- function(obj_, who_new) {
    invisible(.Call('_MASHcpp_RiskQ__push_who', PACKAGE = 'MASHcpp', obj_, who_new))
}

RiskQ__get_pTm <- function(obj_) {
    .Call('_MASHcpp_RiskQ__get_pTm', PACKAGE = 'MASHcpp', obj_)
}

RiskQ__push_pTm <- function(obj_, pTm_new) {
    invisible(.Call('_MASHcpp_RiskQ__push_pTm', PACKAGE = 'MASHcpp', obj_, pTm_new))
}

RiskQ__get_w <- function(obj_) {
    .Call('_MASHcpp_RiskQ__get_w', PACKAGE = 'MASHcpp', obj_)
}

RiskQ__push_w <- function(obj_, w_new) {
    invisible(.Call('_MASHcpp_RiskQ__push_w', PACKAGE = 'MASHcpp', obj_, w_new))
}

RiskQ__add_HumanHost <- function(obj_, who_new, pTm_new, w_new) {
    invisible(.Call('_MASHcpp_RiskQ__add_HumanHost', PACKAGE = 'MASHcpp', obj_, who_new, pTm_new, w_new))
}

RiskQ__get_HumanHost <- function(obj_) {
    .Call('_MASHcpp_RiskQ__get_HumanHost', PACKAGE = 'MASHcpp', obj_)
}

RiskQ__get_HumanHostID <- function(obj_, ID) {
    .Call('_MASHcpp_RiskQ__get_HumanHostID', PACKAGE = 'MASHcpp', obj_, ID)
}

RiskQ__clear_HumanHost <- function(obj_) {
    invisible(.Call('_MASHcpp_RiskQ__clear_HumanHost', PACKAGE = 'MASHcpp', obj_))
}

RiskQ__get_nOther <- function(obj_) {
    .Call('_MASHcpp_RiskQ__get_nOther', PACKAGE = 'MASHcpp', obj_)
}

RiskQ__set_nOther <- function(obj_, nOther_new) {
    invisible(.Call('_MASHcpp_RiskQ__set_nOther', PACKAGE = 'MASHcpp', obj_, nOther_new))
}

RiskQ__add_OtherHost <- function(obj_, otherW_new, typeID_new) {
    invisible(.Call('_MASHcpp_RiskQ__add_OtherHost', PACKAGE = 'MASHcpp', obj_, otherW_new, typeID_new))
}

RiskQ__get_OtherHost <- function(obj_) {
    .Call('_MASHcpp_RiskQ__get_OtherHost', PACKAGE = 'MASHcpp', obj_)
}

MatingQ__ctor <- function() {
    .Call('_MASHcpp_MatingQ__ctor', PACKAGE = 'MASHcpp')
}

MatingQ__get_N <- function(obj_) {
    .Call('_MASHcpp_MatingQ__get_N', PACKAGE = 'MASHcpp', obj_)
}

MatingQ__add_male2Q <- function(obj_, maleID_new, mateFitness_new, maleGenotype_new) {
    invisible(.Call('_MASHcpp_MatingQ__add_male2Q', PACKAGE = 'MASHcpp', obj_, maleID_new, mateFitness_new, maleGenotype_new))
}

MatingQ__get_MatingQ <- function(obj_) {
    .Call('_MASHcpp_MatingQ__get_MatingQ', PACKAGE = 'MASHcpp', obj_)
}

MatingQ__clear_MatingQ <- function(obj_) {
    invisible(.Call('_MASHcpp_MatingQ__clear_MatingQ', PACKAGE = 'MASHcpp', obj_))
}

ImagoQ__ctor <- function() {
    .Call('_MASHcpp_ImagoQ__ctor', PACKAGE = 'MASHcpp')
}

ImagoQ__clear_ImagoQ <- function(obj_) {
    invisible(.Call('_MASHcpp_ImagoQ__clear_ImagoQ', PACKAGE = 'MASHcpp', obj_))
}

ImagoQ__clear_ImagoQTime <- function(obj_, time) {
    invisible(.Call('_MASHcpp_ImagoQ__clear_ImagoQTime', PACKAGE = 'MASHcpp', obj_, time))
}

ImagoQ__add_ImagoQ <- function(obj_, N_new, tEmerge_new, genotype_new) {
    invisible(.Call('_MASHcpp_ImagoQ__add_ImagoQ', PACKAGE = 'MASHcpp', obj_, N_new, tEmerge_new, genotype_new))
}

ImagoQ__track_ImagoQ <- function(obj_, time) {
    .Call('_MASHcpp_ImagoQ__track_ImagoQ', PACKAGE = 'MASHcpp', obj_, time)
}

ImagoQ__get_N <- function(obj_) {
    .Call('_MASHcpp_ImagoQ__get_N', PACKAGE = 'MASHcpp', obj_)
}

ImagoQ__set_N <- function(obj_, N_new) {
    invisible(.Call('_MASHcpp_ImagoQ__set_N', PACKAGE = 'MASHcpp', obj_, N_new))
}

ImagoQ__get_ImagoQ <- function(obj_) {
    .Call('_MASHcpp_ImagoQ__get_ImagoQ', PACKAGE = 'MASHcpp', obj_)
}

ImagoQ__get_ImagoQTime <- function(obj_, tNow, clear) {
    .Call('_MASHcpp_ImagoQ__get_ImagoQTime', PACKAGE = 'MASHcpp', obj_, tNow, clear)
}

EggQ__ctor <- function() {
    .Call('_MASHcpp_EggQ__ctor', PACKAGE = 'MASHcpp')
}

EggQ__clear_EggQ <- function(obj_) {
    invisible(.Call('_MASHcpp_EggQ__clear_EggQ', PACKAGE = 'MASHcpp', obj_))
}

EggQ__clear_EggQTime <- function(obj_, time) {
    invisible(.Call('_MASHcpp_EggQ__clear_EggQTime', PACKAGE = 'MASHcpp', obj_, time))
}

EggQ__add_EggQ <- function(obj_, N_new, tOviposit_new, genotype_new) {
    invisible(.Call('_MASHcpp_EggQ__add_EggQ', PACKAGE = 'MASHcpp', obj_, N_new, tOviposit_new, genotype_new))
}

EggQ__track_EggQ <- function(obj_, time) {
    .Call('_MASHcpp_EggQ__track_EggQ', PACKAGE = 'MASHcpp', obj_, time)
}

EggQ__get_N <- function(obj_) {
    .Call('_MASHcpp_EggQ__get_N', PACKAGE = 'MASHcpp', obj_)
}

EggQ__set_N <- function(obj_, N_new) {
    invisible(.Call('_MASHcpp_EggQ__set_N', PACKAGE = 'MASHcpp', obj_, N_new))
}

EggQ__get_EggQ <- function(obj_) {
    .Call('_MASHcpp_EggQ__get_EggQ', PACKAGE = 'MASHcpp', obj_)
}

EggQ__get_EggQTime <- function(obj_, tNow, clear) {
    .Call('_MASHcpp_EggQ__get_EggQTime', PACKAGE = 'MASHcpp', obj_, tNow, clear)
}

EL4P__ctor <- function(numGenotypes, psi_new, alpha_new, p_new) {
    .Call('_MASHcpp_EL4P__ctor', PACKAGE = 'MASHcpp', numGenotypes, psi_new, alpha_new, p_new)
}

EL4P__oneStep <- function(obj_) {
    invisible(.Call('_MASHcpp_EL4P__oneStep', PACKAGE = 'MASHcpp', obj_))
}

EL4P__oneStep_GEL4P <- function(obj_, M, eqAqua, G, lifespan) {
    invisible(.Call('_MASHcpp_EL4P__oneStep_GEL4P', PACKAGE = 'MASHcpp', obj_, M, eqAqua, G, lifespan))
}

EL4P__burnIn_GEL4P <- function(obj_, M, eqAqua, G, lifespan, tMax) {
    invisible(.Call('_MASHcpp_EL4P__burnIn_GEL4P', PACKAGE = 'MASHcpp', obj_, M, eqAqua, G, lifespan, tMax))
}

EL4P__G2K_GEL4P <- function(obj_, eqAqua, G, lifespan, tMax) {
    invisible(.Call('_MASHcpp_EL4P__G2K_GEL4P', PACKAGE = 'MASHcpp', obj_, eqAqua, G, lifespan, tMax))
}

EL4P__checkDX_GEL4P <- function(obj_, eqAqua, G, lifespan, tMax) {
    .Call('_MASHcpp_EL4P__checkDX_GEL4P', PACKAGE = 'MASHcpp', obj_, eqAqua, G, lifespan, tMax)
}

EL4P__addEggs <- function(obj_, eggs_N, genotype) {
    invisible(.Call('_MASHcpp_EL4P__addEggs', PACKAGE = 'MASHcpp', obj_, eggs_N, genotype))
}

EL4P__get_allGenotypes <- function(obj_) {
    .Call('_MASHcpp_EL4P__get_allGenotypes', PACKAGE = 'MASHcpp', obj_)
}

EL4P__get_genotypeIx <- function(obj_, ix) {
    .Call('_MASHcpp_EL4P__get_genotypeIx', PACKAGE = 'MASHcpp', obj_, ix)
}

EL4P__get_psi <- function(obj_) {
    .Call('_MASHcpp_EL4P__get_psi', PACKAGE = 'MASHcpp', obj_)
}

EL4P__set_psi <- function(obj_, psi_new) {
    invisible(.Call('_MASHcpp_EL4P__set_psi', PACKAGE = 'MASHcpp', obj_, psi_new))
}

EL4P__get_alpha <- function(obj_) {
    .Call('_MASHcpp_EL4P__get_alpha', PACKAGE = 'MASHcpp', obj_)
}

EL4P__set_alpha <- function(obj_, alpha_new) {
    invisible(.Call('_MASHcpp_EL4P__set_alpha', PACKAGE = 'MASHcpp', obj_, alpha_new))
}

EL4P__get_p <- function(obj_) {
    .Call('_MASHcpp_EL4P__get_p', PACKAGE = 'MASHcpp', obj_)
}

EL4P__set_p <- function(obj_, p_new) {
    invisible(.Call('_MASHcpp_EL4P__set_p', PACKAGE = 'MASHcpp', obj_, p_new))
}

EL4P__get_numGenotypes <- function(obj_) {
    .Call('_MASHcpp_EL4P__get_numGenotypes', PACKAGE = 'MASHcpp', obj_)
}

EL4P__get_totalLambda <- function(obj_) {
    .Call('_MASHcpp_EL4P__get_totalLambda', PACKAGE = 'MASHcpp', obj_)
}

EL4P__get_specificLambda <- function(obj_, ix) {
    .Call('_MASHcpp_EL4P__get_specificLambda', PACKAGE = 'MASHcpp', obj_, ix)
}

EL4P__reset <- function(obj_) {
    invisible(.Call('_MASHcpp_EL4P__reset', PACKAGE = 'MASHcpp', obj_))
}

EL4P__set_pop <- function(obj_, initPop) {
    invisible(.Call('_MASHcpp_EL4P__set_pop', PACKAGE = 'MASHcpp', obj_, initPop))
}

ELP__ctor <- function(alpha_new, gamma_new, psi_new, tGrain_new) {
    .Call('_MASHcpp_ELP__ctor', PACKAGE = 'MASHcpp', alpha_new, gamma_new, psi_new, tGrain_new)
}

ELP__oneDay_aquaticDynamics <- function(obj_, eggIn) {
    invisible(.Call('_MASHcpp_ELP__oneDay_aquaticDynamics', PACKAGE = 'MASHcpp', obj_, eggIn))
}

ELP__oneDay_Emergence <- function(obj_) {
    .Call('_MASHcpp_ELP__oneDay_Emergence', PACKAGE = 'MASHcpp', obj_)
}

ELP__ecologicalSimulation <- function(obj_, g, f, v, L_init, M_init, tMax) {
    .Call('_MASHcpp_ELP__ecologicalSimulation', PACKAGE = 'MASHcpp', obj_, g, f, v, L_init, M_init, tMax)
}

ELP__ecologicalSimulation2 <- function(obj_, g_init, f_init, v_init, L_init, M_init, tMax) {
    .Call('_MASHcpp_ELP__ecologicalSimulation2', PACKAGE = 'MASHcpp', obj_, g_init, f_init, v_init, L_init, M_init, tMax)
}

ELP__get_psi <- function(obj_) {
    .Call('_MASHcpp_ELP__get_psi', PACKAGE = 'MASHcpp', obj_)
}

ELP__set_psi <- function(obj_, psi_new) {
    invisible(.Call('_MASHcpp_ELP__set_psi', PACKAGE = 'MASHcpp', obj_, psi_new))
}

ELP__get_alpha <- function(obj_) {
    .Call('_MASHcpp_ELP__get_alpha', PACKAGE = 'MASHcpp', obj_)
}

ELP__set_alpha <- function(obj_, alpha_new) {
    invisible(.Call('_MASHcpp_ELP__set_alpha', PACKAGE = 'MASHcpp', obj_, alpha_new))
}

ELP__get_gamma <- function(obj_) {
    .Call('_MASHcpp_ELP__get_gamma', PACKAGE = 'MASHcpp', obj_)
}

ELP__set_gamma <- function(obj_, gamma_new) {
    invisible(.Call('_MASHcpp_ELP__set_gamma', PACKAGE = 'MASHcpp', obj_, gamma_new))
}

ELP__get_tGrain <- function(obj_) {
    .Call('_MASHcpp_ELP__get_tGrain', PACKAGE = 'MASHcpp', obj_)
}

ELP__get_ELP <- function(obj_) {
    .Call('_MASHcpp_ELP__get_ELP', PACKAGE = 'MASHcpp', obj_)
}

ELP__set_ELP <- function(obj_, L1_new, L2_new, L3_new, L4_new) {
    invisible(.Call('_MASHcpp_ELP__set_ELP', PACKAGE = 'MASHcpp', obj_, L1_new, L2_new, L3_new, L4_new))
}

ELP__get_parameters <- function(obj_) {
    .Call('_MASHcpp_ELP__get_parameters', PACKAGE = 'MASHcpp', obj_)
}

ELP__set_parameters <- function(obj_, alpha_new, gamma_new, psi_new, tGrain_new) {
    invisible(.Call('_MASHcpp_ELP__set_parameters', PACKAGE = 'MASHcpp', obj_, alpha_new, gamma_new, psi_new, tGrain_new))
}

ELP__reset <- function(obj_) {
    invisible(.Call('_MASHcpp_ELP__reset', PACKAGE = 'MASHcpp', obj_))
}

MosquitoFemaleHistory__ctor <- function() {
    .Call('_MASHcpp_MosquitoFemaleHistory__ctor', PACKAGE = 'MASHcpp')
}

MosquitoFemaleHistory__historyInit <- function(obj_, privateEnv) {
    invisible(.Call('_MASHcpp_MosquitoFemaleHistory__historyInit', PACKAGE = 'MASHcpp', obj_, privateEnv))
}

MosquitoFemaleHistory__set_mateID <- function(obj_, mateID_new) {
    invisible(.Call('_MASHcpp_MosquitoFemaleHistory__set_mateID', PACKAGE = 'MASHcpp', obj_, mateID_new))
}

MosquitoFemaleHistory__historyTrack <- function(obj_, privateEnv, alive) {
    invisible(.Call('_MASHcpp_MosquitoFemaleHistory__historyTrack', PACKAGE = 'MASHcpp', obj_, privateEnv, alive))
}

MosquitoFemaleHistory__historyFeed <- function(obj_, privateEnv) {
    invisible(.Call('_MASHcpp_MosquitoFemaleHistory__historyFeed', PACKAGE = 'MASHcpp', obj_, privateEnv))
}

MosquitoFemaleHistory__calcBionomics <- function(obj_) {
    invisible(.Call('_MASHcpp_MosquitoFemaleHistory__calcBionomics', PACKAGE = 'MASHcpp', obj_))
}

MosquitoFemaleHistory__exportHistory <- function(obj_) {
    .Call('_MASHcpp_MosquitoFemaleHistory__exportHistory', PACKAGE = 'MASHcpp', obj_)
}

MosquitoMaleHistory__ctor <- function() {
    .Call('_MASHcpp_MosquitoMaleHistory__ctor', PACKAGE = 'MASHcpp')
}

MosquitoMaleHistory__historyInit <- function(obj_, privateEnv) {
    invisible(.Call('_MASHcpp_MosquitoMaleHistory__historyInit', PACKAGE = 'MASHcpp', obj_, privateEnv))
}

MosquitoMaleHistory__historyTrack <- function(obj_, privateEnv, alive) {
    invisible(.Call('_MASHcpp_MosquitoMaleHistory__historyTrack', PACKAGE = 'MASHcpp', obj_, privateEnv, alive))
}

MosquitoMaleHistory__exportHistory <- function(obj_) {
    .Call('_MASHcpp_MosquitoMaleHistory__exportHistory', PACKAGE = 'MASHcpp', obj_)
}

