# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run a MACRO Simulation
#'
#' write me!
#'
#' @param seed a non-negative integer seed for the prng (the 'mt19937' implementation of the Mersenne Twister is used; see \url{http://www.cplusplus.com/reference/random/mt19937/})
#' @param tmax a non-negative integer maximum simulation time (simulation runs from day 0 to tmax-1)
#' @param human_pars a list of constructor parameters for each human in the simulation
#' @param mosquito_pars a list of constructor parameters for the mosquito population
#' @param patch_pars a list of constructor parameters for each patch in the simulation
#' @param model_pars a list of parameter objects (see \code{\link{pars_obj}}) to initialize parameters object (see inst/include/Parameters.hpp for details)
#' @param log_streams a list giving the output file and name of each logging stream (please ensure that you have provided the right logging stream names for the model(s) you wish to run)
#' @param vaxx_events a list of vaccination events on the human population (for no vaccination events, pass an empty list, \code{list()})
#' @param verbose print information to console?
#'
#' @export
run_macro <- function(seed, tmax, human_pars, mosquito_pars, patch_pars, model_pars, log_streams, vaxx_events, verbose = TRUE) {
    invisible(.Call('_MACRO_run_macro', PACKAGE = 'MACRO', seed, tmax, human_pars, mosquito_pars, patch_pars, model_pars, log_streams, vaxx_events, verbose))
}

#' Utility: Discretize PfSI Event Output to Daily Jump Process
#'
#' Take output of PfSI human infection logging and return a day by day state space data frame.
#'
#' @param out raw output of PfSI in \code{\link{data.frame}} format
#'
#' @export
Util_PfSI_State <- function(out) {
    .Call('_MACRO_Util_PfSI_State', PACKAGE = 'MACRO', out)
}

