# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' PfSI: Write One Human History
#'
#' This is a C++ helper function for \code{\link{util_PfSIHistory}}
#'
#' @param historyIxH a single human history from \code{Human$get_History()}
#' @param timeBins vector of time bins (state transition times)
#' @param timeSeries matrix of occupancy vectors
#'
#'
#' @export
util_PfSIoneHistory <- function(historyIxH, timeBins, timeSeries) {
    invisible(.Call('_MASH_util_PfSIoneHistory', PACKAGE = 'MASH', historyIxH, timeBins, timeSeries))
}

HumanEventQ__ctor <- function(initQ) {
    .Call('_MASH_HumanEventQ__ctor', PACKAGE = 'MASH', initQ)
}

HumanEventQ__firstEvent <- function(obj_) {
    .Call('_MASH_HumanEventQ__firstEvent', PACKAGE = 'MASH', obj_)
}

HumanEventQ__firstTime <- function(obj_) {
    .Call('_MASH_HumanEventQ__firstTime', PACKAGE = 'MASH', obj_)
}

HumanEventQ__rmFirstEventFromQ <- function(obj_) {
    invisible(.Call('_MASH_HumanEventQ__rmFirstEventFromQ', PACKAGE = 'MASH', obj_))
}

HumanEventQ__rmTagFromQ <- function(obj_, tag) {
    invisible(.Call('_MASH_HumanEventQ__rmTagFromQ', PACKAGE = 'MASH', obj_, tag))
}

HumanEventQ__get_queueN <- function(obj_) {
    .Call('_MASH_HumanEventQ__get_queueN', PACKAGE = 'MASH', obj_)
}

HumanEventQ__addEvent2Q <- function(obj_, event) {
    invisible(.Call('_MASH_HumanEventQ__addEvent2Q', PACKAGE = 'MASH', obj_, event))
}

HumanEventQ__get_EventQ <- function(obj_) {
    .Call('_MASH_HumanEventQ__get_EventQ', PACKAGE = 'MASH', obj_)
}

HistoryGeneric__ctor <- function(N) {
    .Call('_MASH_HistoryGeneric__ctor', PACKAGE = 'MASH', N)
}

HistoryGeneric__track_history <- function(obj_, tEvent, event) {
    invisible(.Call('_MASH_HistoryGeneric__track_history', PACKAGE = 'MASH', obj_, tEvent, event))
}

HistoryGeneric__get_history <- function(obj_) {
    .Call('_MASH_HistoryGeneric__get_history', PACKAGE = 'MASH', obj_)
}

HistoryTravel__ctor <- function(N) {
    .Call('_MASH_HistoryTravel__ctor', PACKAGE = 'MASH', N)
}

HistoryTravel__track_travel <- function(obj_, tTravel, locationH) {
    invisible(.Call('_MASH_HistoryTravel__track_travel', PACKAGE = 'MASH', obj_, tTravel, locationH))
}

HistoryTravel__get_travelHistory <- function(obj_) {
    .Call('_MASH_HistoryTravel__get_travelHistory', PACKAGE = 'MASH', obj_)
}

humanPfSI__ctor <- function(PfID_init, tInf_init, b_init, c_init, damID_init, sireID_init, infected_init, chemoprophylaxis_init) {
    .Call('_MASH_humanPfSI__ctor', PACKAGE = 'MASH', PfID_init, tInf_init, b_init, c_init, damID_init, sireID_init, infected_init, chemoprophylaxis_init)
}

humanPfSI__get_PfID <- function(obj_) {
    .Call('_MASH_humanPfSI__get_PfID', PACKAGE = 'MASH', obj_)
}

humanPfSI__push_PfID <- function(obj_, PfID_new) {
    invisible(.Call('_MASH_humanPfSI__push_PfID', PACKAGE = 'MASH', obj_, PfID_new))
}

humanPfSI__back_PfID <- function(obj_) {
    .Call('_MASH_humanPfSI__back_PfID', PACKAGE = 'MASH', obj_)
}

humanPfSI__get_tInf <- function(obj_) {
    .Call('_MASH_humanPfSI__get_tInf', PACKAGE = 'MASH', obj_)
}

humanPfSI__push_tInf <- function(obj_, tInf_new) {
    invisible(.Call('_MASH_humanPfSI__push_tInf', PACKAGE = 'MASH', obj_, tInf_new))
}

humanPfSI__get_b <- function(obj_) {
    .Call('_MASH_humanPfSI__get_b', PACKAGE = 'MASH', obj_)
}

humanPfSI__set_b <- function(obj_, b_new) {
    invisible(.Call('_MASH_humanPfSI__set_b', PACKAGE = 'MASH', obj_, b_new))
}

humanPfSI__get_c <- function(obj_) {
    .Call('_MASH_humanPfSI__get_c', PACKAGE = 'MASH', obj_)
}

humanPfSI__set_c <- function(obj_, c_new) {
    invisible(.Call('_MASH_humanPfSI__set_c', PACKAGE = 'MASH', obj_, c_new))
}

humanPfSI__get_damID <- function(obj_) {
    .Call('_MASH_humanPfSI__get_damID', PACKAGE = 'MASH', obj_)
}

humanPfSI__push_damID <- function(obj_, damID_new) {
    invisible(.Call('_MASH_humanPfSI__push_damID', PACKAGE = 'MASH', obj_, damID_new))
}

humanPfSI__get_sireID <- function(obj_) {
    .Call('_MASH_humanPfSI__get_sireID', PACKAGE = 'MASH', obj_)
}

humanPfSI__push_sireID <- function(obj_, sireID_new) {
    invisible(.Call('_MASH_humanPfSI__push_sireID', PACKAGE = 'MASH', obj_, sireID_new))
}

humanPfSI__get_infected <- function(obj_) {
    .Call('_MASH_humanPfSI__get_infected', PACKAGE = 'MASH', obj_)
}

humanPfSI__set_infected <- function(obj_, infected_new) {
    invisible(.Call('_MASH_humanPfSI__set_infected', PACKAGE = 'MASH', obj_, infected_new))
}

humanPfSI__get_chemoprophylaxis <- function(obj_) {
    .Call('_MASH_humanPfSI__get_chemoprophylaxis', PACKAGE = 'MASH', obj_)
}

humanPfSI__set_chemoprophylaxis <- function(obj_, chemoprophylaxis_new) {
    invisible(.Call('_MASH_humanPfSI__set_chemoprophylaxis', PACKAGE = 'MASH', obj_, chemoprophylaxis_new))
}

humanPfSI__track_history <- function(obj_, tEvent, event) {
    invisible(.Call('_MASH_humanPfSI__track_history', PACKAGE = 'MASH', obj_, tEvent, event))
}

humanPfSI__get_history <- function(obj_) {
    .Call('_MASH_humanPfSI__get_history', PACKAGE = 'MASH', obj_)
}

mosquitoPfSI__ctor <- function(PfID_init, tInf_init, damID_init, sireID_init, infected_init) {
    .Call('_MASH_mosquitoPfSI__ctor', PACKAGE = 'MASH', PfID_init, tInf_init, damID_init, sireID_init, infected_init)
}

mosquitoPfSI__get_PfID <- function(obj_) {
    .Call('_MASH_mosquitoPfSI__get_PfID', PACKAGE = 'MASH', obj_)
}

mosquitoPfSI__set_PfID <- function(obj_, PfID_new) {
    invisible(.Call('_MASH_mosquitoPfSI__set_PfID', PACKAGE = 'MASH', obj_, PfID_new))
}

mosquitoPfSI__get_tInf <- function(obj_) {
    .Call('_MASH_mosquitoPfSI__get_tInf', PACKAGE = 'MASH', obj_)
}

mosquitoPfSI__set_tInf <- function(obj_, tInf_new) {
    invisible(.Call('_MASH_mosquitoPfSI__set_tInf', PACKAGE = 'MASH', obj_, tInf_new))
}

mosquitoPfSI__get_damID <- function(obj_) {
    .Call('_MASH_mosquitoPfSI__get_damID', PACKAGE = 'MASH', obj_)
}

mosquitoPfSI__set_damID <- function(obj_, damID_new) {
    invisible(.Call('_MASH_mosquitoPfSI__set_damID', PACKAGE = 'MASH', obj_, damID_new))
}

mosquitoPfSI__get_sireID <- function(obj_) {
    .Call('_MASH_mosquitoPfSI__get_sireID', PACKAGE = 'MASH', obj_)
}

mosquitoPfSI__set_sireID <- function(obj_, sireID_new) {
    invisible(.Call('_MASH_mosquitoPfSI__set_sireID', PACKAGE = 'MASH', obj_, sireID_new))
}

mosquitoPfSI__get_infected <- function(obj_) {
    .Call('_MASH_mosquitoPfSI__get_infected', PACKAGE = 'MASH', obj_)
}

mosquitoPfSI__set_infected <- function(obj_, infected_new) {
    invisible(.Call('_MASH_mosquitoPfSI__set_infected', PACKAGE = 'MASH', obj_, infected_new))
}

humanPfMOI__ctor <- function(PfID_init, tInf_init, MOI_init, b_init, c_init, damID_init, sireID_init, chemoprophylaxis_init) {
    .Call('_MASH_humanPfMOI__ctor', PACKAGE = 'MASH', PfID_init, tInf_init, MOI_init, b_init, c_init, damID_init, sireID_init, chemoprophylaxis_init)
}

humanPfMOI__get_PfID <- function(obj_) {
    .Call('_MASH_humanPfMOI__get_PfID', PACKAGE = 'MASH', obj_)
}

humanPfMOI__push_PfID <- function(obj_, PfID_new) {
    invisible(.Call('_MASH_humanPfMOI__push_PfID', PACKAGE = 'MASH', obj_, PfID_new))
}

humanPfMOI__get_tInf <- function(obj_) {
    .Call('_MASH_humanPfMOI__get_tInf', PACKAGE = 'MASH', obj_)
}

humanPfMOI__push_tInf <- function(obj_, tInf_new) {
    invisible(.Call('_MASH_humanPfMOI__push_tInf', PACKAGE = 'MASH', obj_, tInf_new))
}

humanPfMOI__get_MOI <- function(obj_) {
    .Call('_MASH_humanPfMOI__get_MOI', PACKAGE = 'MASH', obj_)
}

humanPfMOI__set_MOI <- function(obj_, MOI_new) {
    invisible(.Call('_MASH_humanPfMOI__set_MOI', PACKAGE = 'MASH', obj_, MOI_new))
}

humanPfMOI__get_b <- function(obj_) {
    .Call('_MASH_humanPfMOI__get_b', PACKAGE = 'MASH', obj_)
}

humanPfMOI__set_b <- function(obj_, b_new) {
    invisible(.Call('_MASH_humanPfMOI__set_b', PACKAGE = 'MASH', obj_, b_new))
}

humanPfMOI__get_c <- function(obj_) {
    .Call('_MASH_humanPfMOI__get_c', PACKAGE = 'MASH', obj_)
}

humanPfMOI__set_c <- function(obj_, c_new) {
    invisible(.Call('_MASH_humanPfMOI__set_c', PACKAGE = 'MASH', obj_, c_new))
}

humanPfMOI__get_damID <- function(obj_) {
    .Call('_MASH_humanPfMOI__get_damID', PACKAGE = 'MASH', obj_)
}

humanPfMOI__push_damID <- function(obj_, damID_new) {
    invisible(.Call('_MASH_humanPfMOI__push_damID', PACKAGE = 'MASH', obj_, damID_new))
}

humanPfMOI__get_sireID <- function(obj_) {
    .Call('_MASH_humanPfMOI__get_sireID', PACKAGE = 'MASH', obj_)
}

humanPfMOI__push_sireID <- function(obj_, sireID_new) {
    invisible(.Call('_MASH_humanPfMOI__push_sireID', PACKAGE = 'MASH', obj_, sireID_new))
}

humanPfMOI__get_chemoprophylaxis <- function(obj_) {
    .Call('_MASH_humanPfMOI__get_chemoprophylaxis', PACKAGE = 'MASH', obj_)
}

humanPfMOI__set_chemoprophylaxis <- function(obj_, chemoprophylaxis_new) {
    invisible(.Call('_MASH_humanPfMOI__set_chemoprophylaxis', PACKAGE = 'MASH', obj_, chemoprophylaxis_new))
}

humanPfMOI__add_Infection <- function(obj_, PfID_new, damID_new, sireID_new) {
    invisible(.Call('_MASH_humanPfMOI__add_Infection', PACKAGE = 'MASH', obj_, PfID_new, damID_new, sireID_new))
}

humanPfMOI__clear_Infection <- function(obj_, PfID_ix) {
    invisible(.Call('_MASH_humanPfMOI__clear_Infection', PACKAGE = 'MASH', obj_, PfID_ix))
}

humanPfMOI__get_Infection <- function(obj_) {
    .Call('_MASH_humanPfMOI__get_Infection', PACKAGE = 'MASH', obj_)
}

humanPfMOI__track_history <- function(obj_, tEvent, event) {
    invisible(.Call('_MASH_humanPfMOI__track_history', PACKAGE = 'MASH', obj_, tEvent, event))
}

humanPfMOI__get_history <- function(obj_) {
    .Call('_MASH_humanPfMOI__get_history', PACKAGE = 'MASH', obj_)
}

mosquitoPfMOI__ctor <- function(PfID_init, tInf_init, MOI_init, damID_init, sireID_init) {
    .Call('_MASH_mosquitoPfMOI__ctor', PACKAGE = 'MASH', PfID_init, tInf_init, MOI_init, damID_init, sireID_init)
}

mosquitoPfMOI__get_PfID <- function(obj_) {
    .Call('_MASH_mosquitoPfMOI__get_PfID', PACKAGE = 'MASH', obj_)
}

mosquitoPfMOI__push_PfID <- function(obj_, PfID_new) {
    invisible(.Call('_MASH_mosquitoPfMOI__push_PfID', PACKAGE = 'MASH', obj_, PfID_new))
}

mosquitoPfMOI__get_tInf <- function(obj_) {
    .Call('_MASH_mosquitoPfMOI__get_tInf', PACKAGE = 'MASH', obj_)
}

mosquitoPfMOI__push_tInf <- function(obj_, tInf_new) {
    invisible(.Call('_MASH_mosquitoPfMOI__push_tInf', PACKAGE = 'MASH', obj_, tInf_new))
}

mosquitoPfMOI__get_MOI <- function(obj_) {
    .Call('_MASH_mosquitoPfMOI__get_MOI', PACKAGE = 'MASH', obj_)
}

mosquitoPfMOI__set_MOI <- function(obj_, MOI_new) {
    invisible(.Call('_MASH_mosquitoPfMOI__set_MOI', PACKAGE = 'MASH', obj_, MOI_new))
}

mosquitoPfMOI__get_damID <- function(obj_) {
    .Call('_MASH_mosquitoPfMOI__get_damID', PACKAGE = 'MASH', obj_)
}

mosquitoPfMOI__push_damID <- function(obj_, damID_new) {
    invisible(.Call('_MASH_mosquitoPfMOI__push_damID', PACKAGE = 'MASH', obj_, damID_new))
}

mosquitoPfMOI__get_sireID <- function(obj_) {
    .Call('_MASH_mosquitoPfMOI__get_sireID', PACKAGE = 'MASH', obj_)
}

mosquitoPfMOI__push_sireID <- function(obj_, sireID_new) {
    invisible(.Call('_MASH_mosquitoPfMOI__push_sireID', PACKAGE = 'MASH', obj_, sireID_new))
}

mosquitoPfMOI__add_Infection <- function(obj_, PfID_new, tInf_new, damID_new, sireID_new) {
    invisible(.Call('_MASH_mosquitoPfMOI__add_Infection', PACKAGE = 'MASH', obj_, PfID_new, tInf_new, damID_new, sireID_new))
}

mosquitoPfMOI__get_Infection <- function(obj_, PfID_ix) {
    .Call('_MASH_mosquitoPfMOI__get_Infection', PACKAGE = 'MASH', obj_, PfID_ix)
}

mosquitoPfMOI__get_InfectionIx <- function(obj_, ix) {
    .Call('_MASH_mosquitoPfMOI__get_InfectionIx', PACKAGE = 'MASH', obj_, ix)
}

mosquitoPfMOI__get_InfectionEIP <- function(obj_, incubation) {
    .Call('_MASH_mosquitoPfMOI__get_InfectionEIP', PACKAGE = 'MASH', obj_, incubation)
}

mosquitoPfMOI__which_EIP <- function(obj_, incubation) {
    .Call('_MASH_mosquitoPfMOI__which_EIP', PACKAGE = 'MASH', obj_, incubation)
}

RiskQ__ctor <- function() {
    .Call('_MASH_RiskQ__ctor', PACKAGE = 'MASH')
}

RiskQ__get_N <- function(obj_) {
    .Call('_MASH_RiskQ__get_N', PACKAGE = 'MASH', obj_)
}

RiskQ__set_N <- function(obj_, N_new) {
    invisible(.Call('_MASH_RiskQ__set_N', PACKAGE = 'MASH', obj_, N_new))
}

RiskQ__get_who <- function(obj_) {
    .Call('_MASH_RiskQ__get_who', PACKAGE = 'MASH', obj_)
}

RiskQ__push_who <- function(obj_, who_new) {
    invisible(.Call('_MASH_RiskQ__push_who', PACKAGE = 'MASH', obj_, who_new))
}

RiskQ__get_pTm <- function(obj_) {
    .Call('_MASH_RiskQ__get_pTm', PACKAGE = 'MASH', obj_)
}

RiskQ__push_pTm <- function(obj_, pTm_new) {
    invisible(.Call('_MASH_RiskQ__push_pTm', PACKAGE = 'MASH', obj_, pTm_new))
}

RiskQ__get_w <- function(obj_) {
    .Call('_MASH_RiskQ__get_w', PACKAGE = 'MASH', obj_)
}

RiskQ__push_w <- function(obj_, w_new) {
    invisible(.Call('_MASH_RiskQ__push_w', PACKAGE = 'MASH', obj_, w_new))
}

RiskQ__add_HumanHost <- function(obj_, who_new, pTm_new, w_new) {
    invisible(.Call('_MASH_RiskQ__add_HumanHost', PACKAGE = 'MASH', obj_, who_new, pTm_new, w_new))
}

RiskQ__get_HumanHost <- function(obj_) {
    .Call('_MASH_RiskQ__get_HumanHost', PACKAGE = 'MASH', obj_)
}

RiskQ__get_HumanHostIx <- function(obj_, ix) {
    .Call('_MASH_RiskQ__get_HumanHostIx', PACKAGE = 'MASH', obj_, ix)
}

RiskQ__clear_HumanHost <- function(obj_) {
    invisible(.Call('_MASH_RiskQ__clear_HumanHost', PACKAGE = 'MASH', obj_))
}

RiskQ__get_nOther <- function(obj_) {
    .Call('_MASH_RiskQ__get_nOther', PACKAGE = 'MASH', obj_)
}

RiskQ__set_nOther <- function(obj_, nOther_new) {
    invisible(.Call('_MASH_RiskQ__set_nOther', PACKAGE = 'MASH', obj_, nOther_new))
}

RiskQ__add_OtherHost <- function(obj_, otherW_new, typeID_new) {
    invisible(.Call('_MASH_RiskQ__add_OtherHost', PACKAGE = 'MASH', obj_, otherW_new, typeID_new))
}

RiskQ__get_OtherHost <- function(obj_) {
    .Call('_MASH_RiskQ__get_OtherHost', PACKAGE = 'MASH', obj_)
}

ImagoQ__ctor <- function() {
    .Call('_MASH_ImagoQ__ctor', PACKAGE = 'MASH')
}

ImagoQ__clear_ImagoQ <- function(obj_) {
    invisible(.Call('_MASH_ImagoQ__clear_ImagoQ', PACKAGE = 'MASH', obj_))
}

ImagoQ__clear_ImagoQTime <- function(obj_, time) {
    invisible(.Call('_MASH_ImagoQ__clear_ImagoQTime', PACKAGE = 'MASH', obj_, time))
}

ImagoQ__add_ImagoQ <- function(obj_, N_new, tEmerge_new, genotype_new, damID_new, sireID_new) {
    invisible(.Call('_MASH_ImagoQ__add_ImagoQ', PACKAGE = 'MASH', obj_, N_new, tEmerge_new, genotype_new, damID_new, sireID_new))
}

ImagoQ__track_ImagoQ <- function(obj_, time) {
    .Call('_MASH_ImagoQ__track_ImagoQ', PACKAGE = 'MASH', obj_, time)
}

ImagoQ__get_N <- function(obj_) {
    .Call('_MASH_ImagoQ__get_N', PACKAGE = 'MASH', obj_)
}

ImagoQ__set_N <- function(obj_, N_new) {
    invisible(.Call('_MASH_ImagoQ__set_N', PACKAGE = 'MASH', obj_, N_new))
}

ImagoQ__get_ImagoQ <- function(obj_) {
    .Call('_MASH_ImagoQ__get_ImagoQ', PACKAGE = 'MASH', obj_)
}

ImagoQ__get_ImagoQTime <- function(obj_, tNow, clear) {
    .Call('_MASH_ImagoQ__get_ImagoQTime', PACKAGE = 'MASH', obj_, tNow, clear)
}

EggQ__ctor <- function() {
    .Call('_MASH_EggQ__ctor', PACKAGE = 'MASH')
}

EggQ__clear_EggQ <- function(obj_) {
    invisible(.Call('_MASH_EggQ__clear_EggQ', PACKAGE = 'MASH', obj_))
}

EggQ__clear_EggQTime <- function(obj_, time) {
    invisible(.Call('_MASH_EggQ__clear_EggQTime', PACKAGE = 'MASH', obj_, time))
}

EggQ__add_EggQ <- function(obj_, N_new, tOviposit_new, genotype_new, damID_new, sireID_new) {
    invisible(.Call('_MASH_EggQ__add_EggQ', PACKAGE = 'MASH', obj_, N_new, tOviposit_new, genotype_new, damID_new, sireID_new))
}

EggQ__track_EggQ <- function(obj_, time) {
    .Call('_MASH_EggQ__track_EggQ', PACKAGE = 'MASH', obj_, time)
}

EggQ__get_N <- function(obj_) {
    .Call('_MASH_EggQ__get_N', PACKAGE = 'MASH', obj_)
}

EggQ__set_N <- function(obj_, N_new) {
    invisible(.Call('_MASH_EggQ__set_N', PACKAGE = 'MASH', obj_, N_new))
}

EggQ__get_EggQ <- function(obj_) {
    .Call('_MASH_EggQ__get_EggQ', PACKAGE = 'MASH', obj_)
}

EggQ__get_EggQTime <- function(obj_, tNow, clear) {
    .Call('_MASH_EggQ__get_EggQTime', PACKAGE = 'MASH', obj_, tNow, clear)
}

EL4P__ctor <- function(numGenotypes, psi_new, alpha_new, p_new) {
    .Call('_MASH_EL4P__ctor', PACKAGE = 'MASH', numGenotypes, psi_new, alpha_new, p_new)
}

EL4P__oneStep <- function(obj_) {
    invisible(.Call('_MASH_EL4P__oneStep', PACKAGE = 'MASH', obj_))
}

EL4P__oneStep_GEL4P <- function(obj_, M, eqAqua, G, lifespan) {
    invisible(.Call('_MASH_EL4P__oneStep_GEL4P', PACKAGE = 'MASH', obj_, M, eqAqua, G, lifespan))
}

EL4P__burnIn_GEL4P <- function(obj_, M, eqAqua, G, lifespan, tMax) {
    invisible(.Call('_MASH_EL4P__burnIn_GEL4P', PACKAGE = 'MASH', obj_, M, eqAqua, G, lifespan, tMax))
}

EL4P__G2K_GEL4P <- function(obj_, eqAqua, G, lifespan, tMax) {
    invisible(.Call('_MASH_EL4P__G2K_GEL4P', PACKAGE = 'MASH', obj_, eqAqua, G, lifespan, tMax))
}

EL4P__checkDX_GEL4P <- function(obj_, eqAqua, G, lifespan, tMax) {
    .Call('_MASH_EL4P__checkDX_GEL4P', PACKAGE = 'MASH', obj_, eqAqua, G, lifespan, tMax)
}

EL4P__addEggs <- function(obj_, eggs_N, genotype) {
    invisible(.Call('_MASH_EL4P__addEggs', PACKAGE = 'MASH', obj_, eggs_N, genotype))
}

EL4P__get_allGenotypes <- function(obj_) {
    .Call('_MASH_EL4P__get_allGenotypes', PACKAGE = 'MASH', obj_)
}

EL4P__get_genotypeIx <- function(obj_, ix) {
    .Call('_MASH_EL4P__get_genotypeIx', PACKAGE = 'MASH', obj_, ix)
}

EL4P__get_psi <- function(obj_) {
    .Call('_MASH_EL4P__get_psi', PACKAGE = 'MASH', obj_)
}

EL4P__set_psi <- function(obj_, psi_new) {
    invisible(.Call('_MASH_EL4P__set_psi', PACKAGE = 'MASH', obj_, psi_new))
}

EL4P__get_alpha <- function(obj_) {
    .Call('_MASH_EL4P__get_alpha', PACKAGE = 'MASH', obj_)
}

EL4P__set_alpha <- function(obj_, alpha_new) {
    invisible(.Call('_MASH_EL4P__set_alpha', PACKAGE = 'MASH', obj_, alpha_new))
}

EL4P__get_p <- function(obj_) {
    .Call('_MASH_EL4P__get_p', PACKAGE = 'MASH', obj_)
}

EL4P__set_p <- function(obj_, p_new) {
    invisible(.Call('_MASH_EL4P__set_p', PACKAGE = 'MASH', obj_, p_new))
}

EL4P__get_numGenotypes <- function(obj_) {
    .Call('_MASH_EL4P__get_numGenotypes', PACKAGE = 'MASH', obj_)
}

EL4P__get_totalLambda <- function(obj_) {
    .Call('_MASH_EL4P__get_totalLambda', PACKAGE = 'MASH', obj_)
}

EL4P__get_specificLambda <- function(obj_, ix) {
    .Call('_MASH_EL4P__get_specificLambda', PACKAGE = 'MASH', obj_, ix)
}

EL4P__reset <- function(obj_) {
    invisible(.Call('_MASH_EL4P__reset', PACKAGE = 'MASH', obj_))
}

EL4P__set_pop <- function(obj_, initPop) {
    invisible(.Call('_MASH_EL4P__set_pop', PACKAGE = 'MASH', obj_, initPop))
}

MosquitoFemaleHistory__ctor <- function() {
    .Call('_MASH_MosquitoFemaleHistory__ctor', PACKAGE = 'MASH')
}

MosquitoFemaleHistory__historyInit <- function(obj_, privateEnv) {
    invisible(.Call('_MASH_MosquitoFemaleHistory__historyInit', PACKAGE = 'MASH', obj_, privateEnv))
}

MosquitoFemaleHistory__historyTrack <- function(obj_, privateEnv, alive) {
    invisible(.Call('_MASH_MosquitoFemaleHistory__historyTrack', PACKAGE = 'MASH', obj_, privateEnv, alive))
}

MosquitoFemaleHistory__historyFeed <- function(obj_, privateEnv) {
    invisible(.Call('_MASH_MosquitoFemaleHistory__historyFeed', PACKAGE = 'MASH', obj_, privateEnv))
}

MosquitoFemaleHistory__calcBionomics <- function(obj_) {
    invisible(.Call('_MASH_MosquitoFemaleHistory__calcBionomics', PACKAGE = 'MASH', obj_))
}

MosquitoFemaleHistory__exportHistory <- function(obj_) {
    .Call('_MASH_MosquitoFemaleHistory__exportHistory', PACKAGE = 'MASH', obj_)
}

