\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

Note that $S = a/g$, $x$ = prevalence of infection in humans; $y$ = proportion infected mosquitoes (not infectious); at equilibrium, the proportion infections is $e^{-gn} \bar y = P \bar y$: 
\begin{equation}\begin{array}{rl}
r^{-1} \dot x &= \frac{R_C x}{1 + cSx}(1-x)-x \\  
g^{-1} \dot y &=  cSx (1-y) - y\\  
\end{array}\end{equation}
then for humans: 
\begin{equation}\begin{array}{rl}
R_C (1-\bar x) &= 1 + cS \bar x \\ 
R_C - 1 &= \bar x (R_C + cS) \\
\bar x &= \frac{R_C-1}{R_C + cS}
\end{array}\end{equation}
and for mosquitoes:  
\begin{equation}\begin{array}{rl}
\bar y (1+cS\bar x)  &=  cS\bar x\\
\bar y &= \frac{cS \bar x}{1+ cS \bar x}\\
\bar y &= \frac{cS (R_C -1)}{R_C + cS R_C}\\
\bar y &= \frac{R_C -1}{R_C}\frac{cS}{1+cS}\\
\end{array}\end{equation}
now the force of infection $h$ at equilibrium is: 
\begin{equation}\begin{array}{rl}
\bar h &= \frac{R_C x}{1 + cSx}\\
       &=  \frac{r R_C (R_C-1)}{R_C + cS + cS(R_C -1)} \\
       &=  \frac{r (R_C-1)}{1 + cS} \\ 
\end{array}\end{equation}
\end{document}